#include "ui_localization.h"

#include <array>
#include <fstream>
#include <utility>

#include <nlohmann/json.hpp>

namespace {
using Translation = std::pair<std::string_view, std::string_view>;

// Longest and most specific phrases come first so a shorter fragment cannot
// damage a more useful translation. This also covers formatted counters and
// domain receipts whose numeric values are only known at render time.
constexpr auto kSimplifiedChineseTranslations = std::to_array<Translation>(
    {{"ESC CONTINUES | RAID EXIT RESTORES PRE-RAID SAVE",
      "ESC 继续 | 对局退出会恢复出击前存档"},
     {"CLICK < > TO SELECT | ENTER DEPLOY | ESC CLOSE",
      "点击 < > 选择 | ENTER 出击 | ESC 关闭"},
     {"UP/DOWN SELECT | LEFT/RIGHT ADJUST | SHIFT COARSE | R RESET | F10/ESC "
      "CLOSE",
      "上下选择 | 左右调整 | SHIFT 大步 | R 重置 | F10/ESC 关闭"},
     {"DRAG: MOVE | CTRL: 1 | SHIFT: HALF | R: ROTATE",
      "拖拽：移动 | CTRL：1个 | SHIFT：一半 | R：旋转"},
     {"DAILY 00:00 NEEDS: 8 FOOD / 6 HYGIENE / 5 MORALE / 4 SECURITY",
      "每日 00:00 需求：8 食物 / 6 卫生 / 5 士气 / 4 安全"},
     {"NEXT DAILY NEED IN", "距离下次每日需求"},
     {"RESOLVED DAILY CYCLES", "已结算每日周期"},
     {"WORLD CLOCK SAVE FAILED", "世界时钟保存失败"},
     {"PENDING RAID RETURNS - CHOOSE KEEP OR CONTRIBUTE",
      "待分配对局收获 - 选择保留或捐献"},
     {"NO PENDING ITEMS | BASE IS READY FOR DEPLOY",
      "没有待分配物品 | 基地可以出击"},
     {"ALLOCATION & NEEDS | TEXT/GEOMETRY PLACEHOLDER",
      "资源分配与需求 | 文字/图形占位"},
     {"DEPLOY SAVES A PRE-RAID ROLLBACK POINT", "出击会保存对局前回滚点"},
     {"RETURN / REGROUP TRAVEL", "返程 / 归队耗时"},
     {"NORMAL TRAVEL", "正常返程"},
     {"FAILURE REGROUP", "失败归队"},
     {"DEPART DAY", "出发 第"},
     {"ARRIVE DAY", "抵达 第"},
     {" MIN", " 分钟"},
     {"WARNING: UNSAFE DEPLOY REQUIRES SECOND CONFIRMATION",
      "警告：不安全配装需要再次确认"},
     {"WASD MOVE  SHIFT SPRINT  E INTERACT", "WASD 移动  SHIFT 奔跑  E 交互"},
     {"RAID: LMB FIRE  RMB AIM  R RELOAD  5 MED",
      "对局：左键射击  右键瞄准  R 换弹  5 医疗"},
     {"SHIFT SPRINT  TAB INVENTORY  ESC PAUSE/CLOSE",
      "SHIFT 奔跑  TAB 物品栏  ESC 暂停/关闭"},
     {"TAB INVENTORY  F10 WEAPON TUNING", "TAB 物品栏  F10 武器调试"},
     {"LMB FIRE | RMB AIM | SHIFT SPRINT | R RELOAD",
      "左键射击 | 右键瞄准 | SHIFT 奔跑 | R 换弹"},
     {"RMB MEDICAL ITEM | TAB/ESC CLOSE", "右键使用医疗物品 | TAB/ESC 关闭"},
     {"RMB: ITEM ACTION | TAB/ESC CLOSE", "右键：物品操作 | TAB/ESC 关闭"},
     {"HIGH RISK: CONTINUOUS | SIGNAL EXTRACTION OPEN",
      "高危持续中 | 信号撤离已开放"},
     {" | Active ", " | 存活 "},
     {" | Move ", " | 移动 "},
     {"STASH BLOCKED - INVENTORY PRESERVED", "仓库空间不足 - 物品保持不变"},
     {"ALL CARRIED ASSETS WERE LOST", "所有携带物品均已丢失"},
     {"NO LOST-ITEM LIST IS GENERATED", "失败不生成丢失物品清单"},
     {"RETURNED TO MAIN MENU - NO PERSISTENT PROFILE",
      "已返回主菜单 - 没有持久存档"},
     {"UNSAFE LOADOUT - CONFIRM DEPLOY AGAIN", "配装不安全 - 再次确认出击"},
     {"RESOLVE ALLOCATION & NEEDS BEFORE DEPLOY",
      "出击前请先处理资源分配与需求"},
     {"UNFINISHED RAID RESTORED TO BASE", "未完成对局已恢复到基地"},
     {"PRESS NEW GAME AGAIN TO OVERWRITE", "再次选择新游戏以覆盖存档"},
     {"RAID EXIT RESTORES PRE-RAID SAVE", "退出对局会恢复出击前存档"},
     {"DEVELOPER WEAPON TUNING - RUNTIME ONLY", "开发者武器调试 - 仅本次运行"},
     {"WEAPON ALREADY USES CONTENT DEFAULTS", "武器已使用内容默认值"},
     {"CHANGES ARE NOT SAVED", "调试修改不会保存"},
     {"F10 RUNTIME WEAPON TUNING", "F10 运行时武器调试"},
     {"F10 / ESC CLOSE", "F10 / ESC 关闭"},
     {"HOLD 5 / POINT / RELEASE", "按住 5 / 指向 / 松开"},
     {"BASE STASH - READ ONLY", "基地仓库 - 只读"},
     {"STASH - READ ONLY", "仓库 - 只读"},
     {"NORMAL - GRACE", "常规撤离 - 宽限中"},
     {"NORMAL EXTRACTION", "常规撤离"},
     {"SIGNAL EXTRACTION", "信号撤离"},
     {"LIGHT EXTRACTION LOCKED", "轻装撤离未开放"},
     {"ADVANCED RESOURCE OPEN", "高级资源区已开放"},
     {"ADVANCED RESOURCE LOCKED", "高级资源区未开放"},
     {"HIGH RISK ACTIVE", "高危状态已激活"},
     {"HIGH RISK CONTROL", "高危控制装置"},
     {"F: OPEN CABINET", "F：打开柜体"},
     {"F: SEARCH CABINET", "F：搜索柜体"},
     {"RETURN TO BASE", "返回基地"},
     {"CONTINUE GAME", "继续游戏"},
     {"CONFIRM NEW GAME", "确认新游戏"},
     {"NEW GAME", "新游戏"},
     {"EXIT TO MAIN MENU", "退出到主菜单"},
     {"EXIT TO DESKTOP", "退出到桌面"},
     {"KEYBOARD & MOUSE", "键盘与鼠标"},
     {"CORE EXTRACTION ALPHA", "核心撤离 Alpha"},
     {"PROJECT RAIDLINE", "Project Raidline"},
     {"SIMPLIFIED CHINESE", "简体中文"},
     {"LANGUAGE UPDATED", "语言设置已更新"},
     {"LANGUAGE CHANGED - SETTINGS SAVE FAILED", "语言已切换 - 设置保存失败"},
     {"LANGUAGE", "语言"},
     {"SETTINGS", "设置"},
     {"PAUSED", "已暂停"},
     {"CONTINUE", "继续"},
     {"BACK", "返回"},
     {"EXIT", "退出"},
     {"STORAGE & LOADOUT", "仓储与配装"},
     {"SUPPLY & RECOVERY", "供应与回收"},
     {"ALLOCATION & NEEDS", "资源分配与需求"},
     {"RAID DEPLOYMENT", "对局出击"},
     {"CHARACTER & LOADOUT", "角色与配装"},
     {"STASH - SELECT TO RECYCLE", "仓库 - 选择要回收的物品"},
     {"RECYCLE SELECTED", "回收所选物品"},
     {"CLAIM RELIEF BATCH", "领取救济批次"},
     {"RELIEF NOT REQUIRED", "当前不需要救济"},
     {"KEEP IN STASH", "保留到仓库"},
     {"CONTRIBUTE TO BASE", "捐献给基地"},
     {"CONTRIBUTION BLOCKED", "无法捐献"},
     {"SELECT ITEM FIRST", "请先选择物品"},
     {"KEEP ONLY", "只能保留"},
     {"CONFIRM UNSAFE DEPLOY", "确认不安全出击"},
     {"DEPLOY ALPHA RAID", "进入 Alpha 对局"},
     {"OBJECTIVE COMPLETE", "目标已完成"},
     {"OBJECTIVE: FIND STORAGE", "目标：找到仓储区"},
     {"OBJECTIVE: EQUIP PRIMARY WEAPON", "目标：装备主武器"},
     {"OBJECTIVE: FIND RAID GATE", "目标：找到出击口"},
     {"RAIDLINE BASE", "Raidline 基地"},
     {"RAID RESULT", "对局结果"},
     {"PLAYER DEAD", "玩家死亡"},
     {"RAID ABANDONED", "已放弃对局"},
     {"ABNORMAL EXIT - FAILED", "异常退出 - 失败"},
     {"SETTLEMENT PENDING", "等待结算"},
     {"ENTER / CLICK: RETURN TO BASE", "ENTER / 点击：返回基地"},
     {"EXTRACTION CLOSED", "撤离点关闭"},
     {"SIGNAL LOCKED", "信号撤离未开放"},
     {"HOLD F: TRIGGER", "按住 F：启动"},
     {"NO VALID PRIMARY SAVE", "没有有效主存档"},
     {"RECOVERED SAFE BACKUP", "已恢复安全备份"},
     {"PROFILE LOADED", "存档已载入"},
     {"NEW PROFILE CREATED", "新存档已创建"},
     {"RETURNED TO MAIN MENU", "已返回主菜单"},
     {"DEPLOYMENT IS NOT AVAILABLE", "当前无法出击"},
     {"PENDING ITEM SELECTED", "已选择待分配物品"},
     {"SELECT A PENDING ITEM", "请选择待分配物品"},
     {"STASH HAS NO LEGAL SPACE", "仓库没有合法空间"},
     {"ITEM MOVED TO PERSONAL STASH", "物品已移入个人仓库"},
     {"ITEM CONTRIBUTED TO BASE", "物品已捐献给基地"},
     {"SELECTED FOR RECYCLE", "已选择回收物"},
     {"RELIEF BATCH ADDED TO STASH", "救济批次已加入仓库"},
     {"EQUIPMENT UPDATED", "装备已更新"},
     {"INVENTORY UPDATED", "物品栏已更新"},
     {"NO WEAPON EQUIPPED", "未装备武器"},
     {"WEAPON ALREADY CHAMBERED", "枪膛已有弹药"},
     {"WEAPON CHAMBERED", "已上膛"},
     {"NO ROUND AVAILABLE", "没有可用弹药"},
     {"SELECT AN ASSET FIRST", "请先选择物品"},
     {"SELECT A MAGAZINE TO FILL", "请选择要压弹的弹匣"},
     {"NO COMPATIBLE STASH AMMUNITION", "仓库没有兼容弹药"},
     {"MAGAZINE FILLED", "弹匣已装满"},
     {"MAGAZINE UNLOADED TO STASH", "弹匣已卸入仓库"},
     {"NO COMPATIBLE EQUIPPED WEAPON", "没有兼容的已装备武器"},
     {"MAGAZINE INSTALLED", "弹匣已安装"},
     {"ASSET SELECTED", "已选择物品"},
     {"SELECT A CARRIED MEDKIT WHILE INJURED", "受伤时请选择携带的医疗包"},
     {"MEDKIT ACTION STARTED", "医疗包动作已开始"},
     {"CARRIED ASSET SELECTED", "已选择携带物品"},
     {"CARRIED INVENTORY UPDATED", "随身物品栏已更新"},
     {"ROTATED", "已旋转"},
     {"NO QUICK-TRANSFER SPACE", "没有快速转移空间"},
     {"INVENTORY CHANGED - TRY AGAIN", "物品栏已变化 - 请重试"},
     {"MAGAZINE UNINSTALLED", "弹匣已卸下"},
     {"MAGAZINE PACKING STARTED", "压弹动作已开始"},
     {"AMMUNITION CANNOT BE LOADED", "弹药无法装入"},
     {"MAGAZINE LOADED", "弹匣已装填"},
     {"RELOAD STARTED (2 SEC)", "换弹已开始（2秒）"},
     {"MAGAZINE CANNOT BE INSTALLED", "弹匣无法安装"},
     {"WEAPON MAINTENANCE STARTED (8 SEC)", "武器维修已开始（8秒）"},
     {"WEAPON CANNOT BE MAINTAINED", "武器无法维修"},
     {"ARMOR REPAIR STARTED (6 SEC)", "防具维修已开始（6秒）"},
     {"ARMOR CANNOT BE REPAIRED", "防具无法维修"},
     {"ASSET NO LONGER EXISTS", "物品已不存在"},
     {"MAGAZINE UNLOAD STARTED (3 SEC)", "卸弹已开始（3秒）"},
     {"MAGAZINE EMPTY OR NO CARRIED SPACE", "弹匣为空或随身空间不足"},
     {"MEDICAL ITEM CANNOT BE USED", "医疗物品无法使用"},
     {"MAGAZINE UNLOADED", "弹匣已卸弹"},
     {"MEDICAL EFFECT APPLIED", "医疗效果已应用"},
     {"WEAPON MALFUNCTION CLEARED", "武器故障已排除"},
     {"DEVELOPER WEAPON TUNING OPEN", "开发者武器调试已打开"},
     {"DEVELOPER WEAPON TUNING CLOSED", "开发者武器调试已关闭"},
     {"RUNTIME WEAPON TUNING UPDATED", "运行时武器参数已更新"},
     {"RUNTIME WEAPON TUNING RESET", "运行时武器参数已重置"},
     {"MEDICAL SELECTION CANCELLED", "已取消医疗选择"},
     {"NO CHEST RIG MEDICAL ITEM", "胸挂中没有医疗物品"},
     {"MEDICAL ACTION STARTED", "医疗动作已开始"},
     {"SELECTED MEDICAL ITEM IS NOT APPLICABLE", "所选医疗物品当前不适用"},
     {"UNLOAD MAGAZINE (3 SEC)", "卸出弹药（3秒）"},
     {"UNLOAD ALL TO STASH", "全部卸入仓库"},
     {"USE MEDKIT (5 SEC)", "使用医疗包（5秒）"},
     {"USE MEDKIT", "使用医疗包"},
     {"APPLY BANDAGE (2 SEC)", "使用绷带（2秒）"},
     {"APPLY BANDAGE", "使用绷带"},
     {"APPLY TOURNIQUET (4 SEC)", "使用止血带（4秒）"},
     {"APPLY TOURNIQUET", "使用止血带"},
     {"TAKE PAINKILLER (2 SEC)", "服用止痛药（2秒）"},
     {"TAKE PAINKILLER", "服用止痛药"},
     {"CHAMBER ROUND", "手动上膛"},
     {"RELOADING", "换弹中"},
     {"PACKING MAGAZINE", "压弹中"},
     {"HEALING", "治疗中"},
     {"BANDAGING", "包扎中"},
     {"APPLYING TOURNIQUET", "使用止血带中"},
     {"TAKING PAINKILLER", "服用止痛药中"},
     {"UNLOADING MAGAZINE", "卸弹中"},
     {"MAINTAINING WEAPON", "维修武器中"},
     {"REPAIRING ARMOR", "维修防具中"},
     {"SWITCHING WEAPON", "切换武器中"},
     {"EXTRACTING", "撤离中"},
     {"HEAVY BLEEDING", "重度流血"},
     {"LIGHT BLEEDING", "轻度流血"},
     {"NO BLEEDING", "未流血"},
     {"HEAVY BLEED", "重度流血"},
     {"LIGHT BLEED", "轻度流血"},
     {"NO BLEED", "未流血"},
     {"ARMOR HIT", "护甲受击"},
     {"READY", "可执行"},
     {"NOT NEEDED", "无需使用"},
     {"OVERRIDDEN", "已覆盖"},
     {"CONTENT DEFAULT", "内容默认值"},
     {"NO ACTIVE WEAPON", "没有当前武器"},
     {"EMPTY", "空"},
     {"BLOCKED", "不可执行"},
     {"INSTALL", "安装"},
     {"REPAIR", "维修"},
     {"MERGE", "合并"},
     {"SWAP", "交换"},
     {"LOAD", "装填"},
     {"MOVE", "移动"},
     {"DROP", "丢弃"},
     {"PLAYER", "玩家"},
     {"CONTAINER", "容器"},
     {"ONLY", "仅限"},
     {"EXTRACTED", "撤离成功"},
     {"FOOD", "食物"},
     {"HYGIENE", "卫生"},
     {"MORALE", "士气"},
     {"SECURITY", "安全"},
     {"STABLE", "稳定"},
     {"STRAINED", "紧张"},
     {"CRITICAL", "危急"},
     {"Greyline Depot", "灰线仓库"},
     {"Riverside Checkpoint", "河畔检查站"},
     {"Ashworks Yard", "灰烬工场"},
     {"BALANCED | OPEN CENTER | LONG FLANKS", "均衡 | 中央开阔 | 长线侧路"},
     {"MID-RANGE | CHOKEPOINTS | SAFE OUTER LOOP",
      "中距离 | 咽喉点 | 安全外围环线"},
     {"CLOSE COVER | SPLIT LANES | RISKY CENTER",
      "近距掩体 | 分离路线 | 高风险中央"},
     {"Weapon Maintenance Kit", "武器维修工具"},
     {"15-round Pistol Magazine", "15发手枪弹匣"},
     {"30-round Magazine", "30发弹匣"},
     {"Damaged Electronics", "损坏电子元件"},
     {"Armor Repair Kit", "防具维修工具"},
     {"Basic Body Armor", "基础防弹衣"},
     {"Basic Helmet", "基础头盔"},
     {"Small Chest Rig", "小型胸挂"},
     {"Small Backpack", "小型背包"},
     {"9mm Ammunition", "9毫米弹药"},
     {"Medical Kit", "医疗包"},
     {"Basic Medkit", "基础医疗包"},
     {"Tourniquet", "止血带"},
     {"Painkiller", "止痛药"},
     {"Bandage", "绷带"},
     {"Scrap Parts", "废旧零件"},
     {"Pistol", "手枪"},
     {"Rifle", "步枪"},
     {"Cola", "可乐"},
     {"BODY ARMOR", "防弹衣"},
     {"CHEST RIG", "胸挂"},
     {"BACKPACK", "背包"},
     {"HELMET", "头盔"},
     {"LONG GUN", "长枪"},
     {"SIDEARM", "手枪"},
     {"MAG", "弹匣"},
     {"UTIL", "工具"},
     {"CURRENCY", "货币"},
     {"DURABILITY", "耐久"},
     {"CONDITION", "状态"},
     {"CAPACITY", "容量"},
     {"AMMUNITION", "弹药"},
     {"AMMO", "弹药"},
     {"HEALTH", "生命"},
     {"OBJECTIVE", "目标"},
     {"SCORE", "得分"},
     {"RAID", "对局"},
     {"STASH", "仓库"},
     {"UNKNOWN", "未知"},
     {"medical asset does not exist", "医疗物品不存在"},
     {"medical asset is not carried into the Raid", "医疗物品未携带进对局"},
     {"medical asset has no usable charge", "医疗物品没有可用次数"},
     {"medical effect is not applicable", "医疗效果当前不适用"},
     {"allocation item does not exist", "待分配物品不存在"},
     {"only pending allocation items can be contributed",
      "只有待分配物品可以捐献"},
     {"a non-empty container cannot be contributed", "非空容器不能捐献"},
     {"item has no Base contribution value", "物品没有基地贡献值"},
     {"supply definition does not exist", "供应定义不存在"},
     {"item is not available from fixed supply", "固定供应中没有该物品"},
     {"currency is insufficient", "货币不足"},
     {"asset cannot be recycled", "物品不能回收"},
     {"currency would overflow", "货币数值会溢出"},
     {"profile is not eligible for relief", "当前不符合救济条件"},
     {"requested quantity is outside the source stack", "请求数量超出来源堆叠"},
     {"requested orientation is not supported", "不支持请求的方向"},
     {"only Settlement can place assets into pending allocation",
      "只有结算可以把物品放入待分配区"},
     {"destination container does not exist", "目标容器不存在"},
     {"asset does not fit inside the destination", "物品无法放入目标位置"},
     {"pending allocation cannot swap an asset back into intake",
      "待分配物品不能通过交换返回待分配区"},
     {"partial movement requires a stackable empty or matching target",
      "部分移动需要空位或同类可堆叠目标"},
     {"selected quantity cannot be merged completely", "所选数量无法完整合并"},
     {"destination asset disappeared", "目标物品已不存在"},
     {"stacks from different relief batches cannot be combined",
      "不同救济批次的堆叠不能合并"},
     {"destination stack is full", "目标堆叠已满"},
     {"destination overlaps more than one asset", "目标位置与多个物品重叠"},
     {"pending allocation must be kept before it can be equipped",
      "待分配物品需先保留到仓库才能装备"},
     {"asset cannot use the requested equipment slot",
      "物品不能使用该装备栏位"},
     {"occupied equipment slot cannot be swapped", "已占用装备栏位无法交换"},
     {"magazine or ammunition does not exist", "弹匣或弹药不存在"},
     {"ammunition is incompatible with magazine", "弹药与弹匣不兼容"},
     {"requested rounds do not fit", "请求的弹药数量无法装入"},
     {"magazine has no rounds to unload", "弹匣没有可卸出的弹药"},
     {"destination cannot hold unloaded ammunition",
      "目标位置无法容纳卸出的弹药"},
     {"weapon or magazine does not exist", "武器或弹匣不存在"},
     {"magazine is incompatible with weapon", "弹匣与武器不兼容"},
     {"magazine must be stored before installation",
      "弹匣安装前必须位于容器中"},
     {"weapon or magazine disappeared during installation",
      "安装期间武器或弹匣已不存在"},
     {"weapon has no installed magazine", "武器没有已安装弹匣"},
     {"asset is not a magazine-fed weapon", "物品不是弹匣供弹武器"},
     {"weapon is already chambered", "武器已上膛"},
     {"no round is available to chamber", "没有可上膛的弹药"},
     {"weapon malfunction must be cleared", "必须先排除武器故障"},
     {"weapon has no malfunction", "武器没有故障"},
     {"weapon is broken", "武器已损坏"},
     {"weapon is dry", "武器无弹"},
     {"round chambered", "弹药已上膛"},
     {"maintenance kit or weapon does not exist", "维修工具或武器不存在"},
     {"maintenance kit cannot repair itself", "维修工具不能维修自身"},
     {"maintenance capability or capacity is unavailable",
      "维修能力或容量不足"},
     {"weapon does not require maintenance", "武器当前无需维修"},
     {"maintenance would produce no result", "维修不会产生效果"},
     {"maintenance kit has no usable capacity", "维修工具没有可用容量"},
     {"armor repair kit or armor does not exist", "防具维修工具或防具不存在"},
     {"armor repair kit cannot repair itself", "防具维修工具不能维修自身"},
     {"armor maintenance capability or capacity is unavailable",
      "防具维修能力或容量不足"},
     {"armor does not require maintenance", "防具当前无需维修"},
     {"armor material has no maintenance cost", "防具材料没有维修消耗定义"},
     {"armor repair kit cannot produce a legal repair",
      "防具维修工具无法完成合法维修"},
     {"armor repair cost exceeds kit capacity", "防具维修消耗超过工具容量"},
     {"transaction ID must not be empty", "事务编号不能为空"},
     {"profile revision is stale", "存档版本已过期"},
     {"profile revision cannot advance", "存档版本无法推进"},
     {"asset does not exist", "物品不存在"},
     {"weapon does not exist", "武器不存在"},
     {"magazine does not exist", "弹匣不存在"},
     {"persistence is not configured", "存档系统未配置"},
     {"weapon malfunction", "武器故障"},
     {"medical charge could not be committed", "医疗次数提交失败"},
     {"continuous healing revision overflow", "持续治疗版本溢出"},
     {"continuous healing could not be committed", "持续治疗提交失败"},
     {"continuous healing world sync failed", "持续治疗世界同步失败"},
     {"medical status revision overflow", "医疗状态版本溢出"},
     {"incoming damage could not be committed", "受到伤害提交失败"},
     {"primary save was invalid; recovered safe backup",
      "主存档无效；已恢复安全备份"},
     {"no valid primary or backup save", "没有有效主存档或备份"},
     {"save directory could not be created", "无法创建存档目录"},
     {"temporary save could not be written", "无法写入临时存档"},
     {"temporary save failed read-back validation", "临时存档回读校验失败"},
     {"pending Raid recovery backup could not be prepared",
      "无法准备未完成对局恢复备份"},
     {"safe backup could not be updated", "无法更新安全备份"},
     {"safe backup could not be atomically replaced", "无法原子替换安全备份"},
     {"initial safe backup could not be created", "无法创建初始安全备份"},
     {"primary save could not be atomically replaced", "无法原子替换主存档"},
     {"primary save committed; recovery backup could not be installed",
      "主存档已提交；恢复备份安装失败"},
     {"Recoil control", "后坐力控制"},
     {"Stability", "稳定性"},
     {"Handling speed", "操控速度"},
     {"Ergonomics", "人机工效"},
     {"Accuracy", "精准度"},
     {"Shot interval", "射击间隔"},
     {"Base damage", "基础伤害"},
     {"Effective range", "有效射程"},
     {"Maximum range", "最大射程"},
     {"Logical ballistic speed", "逻辑弹道速度"},
     {"High-scope maximum speed", "高倍镜最大移动速度"},
     {"High-scope control accel", "高倍镜控制加速度"},
     {"Spread per shot", "单发散布增长"},
     {"Recoil lateral ratio", "后坐力横向比例"},
     {"Recoil bend duration", "后坐力偏转时长"},
     {"Moving spread fraction", "移动散布比例"},
     {"Sprinting spread fraction", "奔跑散布比例"},
     {"Reticle motion spread rate", "准星移动散布速率"},
     {"Near-distance spread scale", "近距离散布缩放"},
     {"Effective-range distance bloom", "有效射程距离扩散"},
     {"Right-click aim accuracy", "右键瞄准精准度"},
     {"Right-click aim stability", "右键瞄准稳定性"},
     {"Weak tracer length", "弱曳光长度"},
     {"Weak tracer opacity", "弱曳光透明度"},
     {"Weak tracer lifetime", "弱曳光持续时间"},
     {"recoil speed", "后坐速度"},
     {"max spread", "最大散布"},
     {"recovery", "恢复"},
     {"control accel", "控制加速度"},
     {"min spread", "最小散布"},
     {"charge(s)", "次"},
     {"ASSET", "物品"},
     {"Stationary", "静止"},
     {"Normal", "常规"},
     {"Attack", "攻击"},
     {"Unaware", "未警觉"},
     {"Alerted", "已警觉"},
     {"Searching", "搜索中"},
     {"Engage", "交战"},
     {"Support", "支援"},
     {"Grab", "抓取"},
     {"Scratch", "抓挠"},
     {"Bite", "撕咬"},
     {"Idle", "待机"},
     {"Windup", "前摇"},
     {"Active", "生效"},
     {"Recovery", "后摇"},
     {"OffBalance", "失衡"},
     {"Unknown", "未知"},
     {"Action: None", "操作：无"},
     {"Action: MoveUp", "操作：向上移动"},
     {"Action: MoveDown", "操作：向下移动"},
     {"Action: MoveLeft", "操作：向左移动"},
     {"Action: MoveRight", "操作：向右移动"},
     {"Action: Fire", "操作：射击"},
     {"Action: Interact", "操作：交互"},
     {"Action: ToggleInventory", "操作：切换物品栏"},
     {"Action: Sprint", "操作：奔跑"},
     {"Player HP", "玩家生命"},
     {"Enemies", "敌人"},
     {"Alerted", "已警觉"},
     {"Searching", "搜索中"},
     {"Ground Items", "地面物品"},
     {"Inventory Items", "物品栏物品"},
     {"Interact", "交互"},
     {"Inventory: Cabinet [Open]", "物品栏：柜体[已打开]"},
     {"Inventory: Player [Open]", "物品栏：玩家[已打开]"},
     {"Inventory: Tab [Closed]", "物品栏：Tab[已关闭]"},
     {"Raid Time: NO HARD LIMIT", "对局时间：无硬性限制"},
     {"Raid Time", "对局时间"},
     {"NORMAL EXTRACTION OPEN", "常规撤离已开放"},
     {"HIGH RISK SOON", "即将进入高危"},
     {"REGULAR", "常规阶段"},
     {"Pressure wave", "压力波次"},
     {"Profile assets", "存档物品"},
     {"Currency", "货币"},
     {"stacks", "堆"},
     {"units", "件"},
     {"Settlement", "结算"},
     {"Flow", "流程"},
     {"Session", "会话"},
     {"Enemy AI: none", "敌人 AI：无"},
     {"Enemy AI: defeated", "敌人 AI：已击败"},
     {"Lead AI", "领队 AI"},
     {"moving", "移动中"},
     {"holding", "原地警戒"},
     {"stagger", "硬直"},
     {"Player controlled: no", "玩家受控：否"},
     {"Player controlled", "玩家受控"},
     {"Weapon: NONE", "武器：无"},
     {"Chamber", "枪膛"},
     {"Magazine", "弹匣"},
     {"MALFUNCTION - SWEEP MOUSE", "故障 - 快速移动鼠标排除"},
     {"PAIN SUPPRESSED", "疼痛已抑制"},
     {"PAIN", "疼痛"},
     {"Extraction", "撤离"},
     {"STORED", "已存入"},
     {"STACKS", "堆"},
     {"UNITS", "件"},
     {"LOST", "丢失"},
     {"Resolve Stash capacity before returning", "返回前请先解决仓库容量"},
     {"RECOIL DECEL", "后坐减速度"},
     {"RMB AIM", "右键瞄准"},
     {"DUR", "耐久"},
     {"SUPPLY & RECOVERY", "供应与回收"},
     {"BUY", "购买"},
     {"RECYCLE", "回收"},
     {"RELIEF-LOCKED", "救济锁定"},
     {"LAST SHORTFALL", "上次短缺"},
     {"SHORTAGE NEVER BLOCKS PLAY", "短缺不会阻止游玩"},
     {"NIGHT", "夜晚"},
     {"DAY", "白天"},
     {"MAP", "地图"},
     {"CAN FIRE NOW", "当前可射击"},
     {"COMPATIBLE MAGAZINE ROUNDS", "发兼容弹匣弹药"},
     {"NEEDS CHAMBER/RELOAD", "需要上膛/换弹"},
     {"COMPATIBLE ROUNDS", "发兼容弹药"},
     {"NO USABLE AMMUNITION", "没有可用弹药"},
     {"DEPLOY BLOCKED", "无法出击"},
     {"PENDING ITEM(S) AT", "件待分配物品位于"},
     {"REV", "版本"},
     {"BASE", "基地"},
     {"HP", "生命"},
     {"Score", "得分"},
     {"Raid", "对局"},
     {"NONE", "无"},
     {"Medical Ki", "医疗包"},
     {"9mm Ammuni", "9毫米弹药"},
     {"30-round M", "30发弹匣"},
     {"15-round P", "15发手枪弹匣"},
     {"Small Ches", "小型胸挂"},
     {"Small Back", "小型背包"},
     {"Basic Medk", "基础医疗包"},
     {"Weapon Mai", "武器维修工具"},
     {"Armor Repa", "防具维修工具"},
     {"Basic Helm", "基础头盔"},
     {"Basic Body", "基础防弹衣"},
     {"Scrap Part", "废旧零件"},
     {"Damaged El", "损坏电子元件"}});

void replaceAll(std::string &text, std::string_view source,
                std::string_view destination) {
  std::size_t offset{};
  while ((offset = text.find(source, offset)) != std::string::npos) {
    text.replace(offset, source.size(), destination);
    offset += destination.size();
  }
}
} // namespace

const char *uiLanguageCode(UiLanguage language) noexcept {
  return language == UiLanguage::SimplifiedChinese ? "zh-CN" : "en-US";
}

const char *uiLanguageDisplayName(UiLanguage language) noexcept {
  return language == UiLanguage::SimplifiedChinese ? "简体中文" : "English";
}

UiLanguage toggledUiLanguage(UiLanguage language) noexcept {
  return language == UiLanguage::SimplifiedChinese
             ? UiLanguage::English
             : UiLanguage::SimplifiedChinese;
}

std::string localizeUiText(UiLanguage language, std::string_view englishText) {
  std::string localized{englishText};
  if (language == UiLanguage::English || localized.empty()) {
    return localized;
  }
  for (const auto &[english, chinese] : kSimplifiedChineseTranslations) {
    replaceAll(localized, english, chinese);
  }
  return localized;
}

UiLanguage loadUiLanguage(const std::filesystem::path &settingsPath) noexcept {
  try {
    std::ifstream stream{settingsPath};
    if (!stream) {
      return UiLanguage::SimplifiedChinese;
    }
    nlohmann::json document;
    stream >> document;
    const std::string code = document.value("language", "zh-CN");
    return code == "en-US" ? UiLanguage::English
                           : UiLanguage::SimplifiedChinese;
  } catch (...) {
    return UiLanguage::SimplifiedChinese;
  }
}

bool saveUiLanguage(const std::filesystem::path &settingsPath,
                    UiLanguage language) noexcept {
  try {
    std::filesystem::create_directories(settingsPath.parent_path());
    std::ofstream stream{settingsPath, std::ios::trunc};
    if (!stream) {
      return false;
    }
    stream << nlohmann::json{{"language", uiLanguageCode(language)}}.dump(2);
    stream.flush();
    return stream.good();
  } catch (...) {
    return false;
  }
}
