#include "ui_localization.h"

#include <array>
#include <fstream>
#include <utility>

#include <nlohmann/json.hpp>

namespace {
using Translation = std::pair<std::string_view, std::string_view>;

// Longest and most specific phrases come first so a shorter fragment cannot
// damage a more useful translation. This also covers formatted counters and
// domain receipts whose numeric values are only known at render time.
constexpr auto kSimplifiedChineseTranslations = std::to_array<Translation>(
    {{"ROLE READY | EQUIPMENT AND CARRIED AMMO MATCH",
       "职责准备完成 | 装备和随身弹药符合要求"},
     {"LOADOUT ROLE SELECTED | REVIEW REAL GAPS BELOW",
      "已选择配装职责 | 请查看下方真实缺口"},
     {"Light Scavenger", "轻型搜刮"},
     {"Balanced Operator", "均衡作战"},
     {"Heavy Specialist", "重型专精"},
     {"ROLE TARGET | ", "职责目标 | "},
     {"CARRIED AMMO", "随身兼容弹药"},
     {"GAPS", "有缺口"},
     {"CRISIS: UNKNOWN | ENEMY DOSSIER REVEALS BEFORE ACTIVATION",
       "危机：未知 | 携带敌情档案可在激活前获知详情"},
     {"LARGER WAVES CONVERGE ON A FACTORY CACHE",
      "更大规模敌群正向厂区物资点汇聚"},
     {"FAST PRESSURE ALONG THE ROAD NETWORK",
      "敌群正沿道路网络快速汇聚"},
     {"VALUABLE CARGO DRAWS STEADY PRESSURE",
      "高价值货物正在持续吸引敌群"},
     {"PRESSURE CONVERGING ON MARKED TARGET",
      "敌群正在向地图标记目标汇聚"},
     {"Converging on crisis target", "正向危机目标汇聚"},
     {"HIGH-RISK CRISIS ACTIVE", "高危危机已激活"},
     {"CRISIS TARGET", "危机目标"},
     {"Industrial Breach", "工业缺口"},
     {"Road Convergence", "公路汇流"},
     {"Freight Lockdown", "货运封锁"},
     {"Pressure converges on exposed road approaches.",
      "敌群正在向暴露的公路入口汇聚。"},
     {"Dense pressure breaks through industrial service lanes.",
      "密集敌群正从工业维修通道突破。"},
     {"Freight routes are closing around secured cargo.",
      "货运通道正围绕加固货物区收紧。"},
     {"CRISIS: ", "危机："},
     {"PACING SOFTWARE DEADLINE | TARGET ",
      "帧节奏 软件截止时间 | 目标 "},
     {"PACING VSYNC + DEADLINE | TARGET ",
      "帧节奏 垂直同步加截止时间 | 目标 "},
     {"PROP: ENGINEERING EQUIPMENT", "工程设备"},
     {"PROP: ROAD BARRIER", "道路障碍"},
     {"PROP: WAREHOUSE", "仓库"},
     {"PROP: CONTAINER", "集装箱"},
     {"PROP: FACTORY", "厂房"},
     {"PROP: TRUCK", "卡车"},
     {"PROP: DEBRIS", "碎屑"},
     {"PROP: UNKNOWN", "未知环境物"},
     {"PROP: CAR", "车辆"},
     {"FREIGHT EXCHANGE COMPLEX", "货运换装中心"},
     {"HIGHWAY SERVICE PLAZA", "公路服务中心"},
     {"CONSTRUCTION OPEN GROUND", "施工空地"},
     {"HIGHWAY INTERCHANGE", "公路换装区"},
     {"DRAINAGE GREENBELT", "排水绿地"},
     {"FABRICATION PLANT", "制造厂区"},
     {"INDUSTRIAL PLANT", "工业厂区"},
     {"MAINTENANCE CACHE", "维修物资点"},
     {"ROADSIDE SALVAGE", "路旁回收点"},
     {"SECURED CARGO", "加固货物点"},
     {"FREIGHT MANIFEST CACHE", "货运清单物资点"},
     {"FABRICATION STOCK", "制造厂库存点"},
     {"SERVICE PLAZA SUPPLIES", "服务区补给点"},
     {"RISK TIER", "风险等级"},
     {"LOGISTICS YARD", "物流堆场"},
     {"ROADSIDE SERVICE", "公路服务区"},
     {"PERIMETER SECURED | EXTRACT TO REDUCE BASE THREAT",
      "基地外围已清剿 | 撤离后降低基地威胁"},
     {"PERIMETER SWEEP | INITIAL HOSTILES REMAINING ",
      "基地外围清剿 | 初始敌人剩余 "},
     {"PERIMETER SWEEP LOCKED | THREAT ",
      "基地外围清剿未开放 | 威胁 "},
     {"CONFIRM PERIMETER SWEEP | THREAT ",
      "确认基地外围清剿 | 威胁 "},
     {"PERIMETER SWEEP | THREAT ", "基地外围清剿 | 威胁 "},
     {" | SUCCESS -", " | 成功清剿 -"},
     {" | RAID +", " | 行动 +"},
     {" | NORMAL EXITS OPEN", " | 常规撤离开放"},
     {"BASE THREAT REDUCED: -", "基地威胁降低：-"},
     {"Base perimeter sweep is unavailable during a Raid",
      "对局期间不能发起基地外围清剿"},
     {"Base siege warning must be resolved first",
      "必须先处理基地攻城预警"},
     {"Base threat is below the perimeter sweep threshold",
      "基地威胁尚未达到外围清剿门槛"},
     {"RAIDS AVAILABLE | 3-MIN WARNING AFTER SAFETY",
      "安全期内可正常出击 | 安全期结束后进入3分钟预警"},
     {"BASE SIEGE QUEUED | SAFETY ",
      "基地尸潮已排队 | 安全期剩余 "},
     {"BASE DEFENSE FAILED SOFTLY | RECOVERY PERIOD STARTED",
      "基地防守软失败 | 恢复期已开始"},
     {"BASE DEFENDED | SAFETY PERIOD STARTED",
      "基地防守成功 | 安全期已开始"},
     {"PREPARATION COMPLETE | MANUAL CONFIRMATION REQUIRED",
      "准备时间结束 | 需要手动确认"},
     {"FAILURE: LIMITED PUBLIC LOSS, 12 SAFE DAYS, NO PERSONAL GEAR LOSS",
      "失败：有限公共损失、12天安全期、不损失个人装备"},
     {"SUCCESS: MATERIAL +8, MORALE SUPPORT, 7 SAFE DAYS",
      "成功：建材+8、士气支持、7天安全期"},
     {"FIRST SIEGE WILL NOT RESOLVE UNTIL YOU CONFIRM",
      "首次攻城将在你确认后才会结算"},
     {"SAVED PRESET WILL RESOLVE WHEN THE TIMER ENDS",
      "倒计时结束后将使用已保存预设结算"},
     {"THREAT SOURCES | RAID ", "威胁来源 | 对局 "},
     {" | POPULATION ", " | 人口 "},
     {" | SITE ", " | 地点 "},
     {"AUTO DEFENSE | SECURITY ", "自动防守 | 安保 "},
     {"PROJECTED SUCCESS", "预计成功"},
     {"SOFT FAILURE RISK", "存在软失败风险"},
     {"START AUTO DEFENSE NOW", "立即开始自动防守"},
     {"QUEUED", "已排队"},
     {"BASE SIEGE WARNING", "基地尸潮预警"},
     {"PREPARATION ", "准备时间 "},
     {"BASE THREAT ", "基地威胁 "},
     {"Base is not under siege warning", "基地当前没有攻城预警"},
     {"automatic defense is unavailable during a Raid",
      "对局期间不能进行自动防守"},
     {"resolve the Base siege warning before deploying",
      "出击前必须先处理基地攻城预警"},
     {"main Base migration is locked during siege warning",
      "攻城预警期间不能迁徙主基地"},
     {"new construction is locked during siege warning",
      "攻城预警期间不能开始新建设"},
     {"Base facility installation is locked during siege warning",
      "攻城预警期间不能安装设施"},
     {"BASE SITE FEATURE REPAIRED | OPERATIONAL WHILE THIS IS THE MAIN BASE",
      "基地地点设施已修复 | 仅在此处作为主基地时运行"},
     {"REPAIR FEATURE | ", "修复地点设施 | "},
     {" MAT | ", " 建材 | "},
     {" | TIME ", " | 耗时倍率 "},
     {"FEATURE ONLINE | TIME ", "地点设施运行中 | 耗时倍率 "},
     {"REPAIR SITE FEATURE | MATERIAL ", "修复地点设施 | 建材 "},
     {"SITE FEATURE ONLINE | PRODUCTION ", "地点设施运行中 | 制造耗时 "},
     {"SITE FEATURE ONLINE | BASELINE EFFECT",
      "地点设施运行中 | 基础效果"},
     {"SITE FEATURE REPAIR BLOCKED", "地点设施暂时无法修复"},
     {"Base site must be secured before repairing its feature",
      "必须先清剿基地地点才能修复其设施"},
     {"establish the staging outpost before repairing the site feature",
      "修复地点设施前必须先建立前哨"},
     {"Base site feature repair is unavailable during a Raid",
      "对局期间不能修复基地地点设施"},
     {"Base site feature is already repaired", "基地地点设施已经修复"},
     {"workshop must be installed before repairing the site feature",
      "修复地点设施前必须安装普通工坊"},
     {"Base site feature state is missing", "缺少基地地点设施状态"},
     {"OUTPUT ", "产出 "},
     {" | SITE ", " | 地点倍率 "},
     {"MAIN BASE MIGRATION COMPLETE | OLD BASE IS AN OUTPOST",
      "主基地迁徙完成 | 旧基地已转为前哨"},
     {"CLEAR SITE > ESTABLISH STAGING OUTPOST > BUILD CORE FACILITIES > MIGRATE",
      "清剿地点 > 建立前哨 > 建成核心设施 > 迁徙"},
     {"MIGRATION CORE | WAREHOUSE ", "迁徙核心设施 | 仓储区 "},
     {" | DORMITORY FACILITY ", " | 宿舍 "},
     {" | KITCHEN/WATER ", " | 厨房/净水 "},
     {" | MEDICAL FACILITY ", " | 医疗所 "},
     {"MIGRATE MAIN BASE | ", "迁徙主基地 | "},
     {" | OLD BASE BECOMES OUTPOST", " | 旧基地转为前哨"},
     {"MIGRATION BLOCKED | ESTABLISH TARGET OUTPOST",
      "暂时无法迁徙 | 请先建立目标地点前哨"},
     {"BUILD KITCHEN & WATER | MATERIAL ",
      "建设厨房与净水站 | 建材 "},
     {"CANCEL KITCHEN & WATER | ", "取消厨房与净水站建设 | "},
     {"KITCHEN & WATER REQUIREMENTS NOT MET",
      "厨房与净水站建设条件未满足"},
     {"KITCHEN & WATER CONSTRUCTION STARTED",
      "厨房与净水站建设已开始"},
     {"KITCHEN & WATER CONSTRUCTION CANCELLED",
      "厨房与净水站建设已取消"},
     {"KITCHEN & WATER PROJECT IS NOT PUBLISHED",
      "尚未发布厨房与净水站建设项目"},
     {"FACILITY RESERVE | WORKSHOP | INSTALL FREE",
      "设施储备 | 工坊 | 免费安装"},
     {"FACILITY RESERVE | EMPTY", "设施储备 | 空"},
     {"WORKSHOP INSTALLED FROM FACILITY RESERVE",
      "已从设施储备安装工坊"},
     {"WORKSHOP IS IN FACILITY RESERVE | INSTALL IT ON REGIONAL PAGE",
      "工坊位于设施储备 | 请在区域页面安装"},
     {"WORKSHOP & PRODUCTION | FACILITY RESERVE",
      "工坊与生产 | 设施储备"},
     {"WORKSHOP IS PACKED | PRODUCTION AND UPGRADES ARE PAUSED",
      "工坊已打包 | 生产与升级进度暂停"},
     {"INSTALL IT FREE ON THE REGIONAL PAGE TO RESUME EXACT PROGRESS",
      "在区域页面免费安装后将按原进度继续"},
     {"ACTIVE MAIN BASE LOCATION | NOT A LIGHT OUTPOST",
      "当前主基地地点 | 不作为轻量前哨运行"},
     {"MAIN BASE | TECHNOLOGY CORE ACTIVE",
      "主基地 | 科技核心运行中"},
     {"TECHNOLOGY CORE ", "科技核心 "},
     {"target Base site outpost must be established first",
      "必须先在目标基地地点建立前哨"},
     {"required migration facilities are missing",
      "缺少主基地迁徙所需设施"},
     {"target Base site is locked", "目标基地地点尚未解锁"},
     {"main Base migration is unavailable during a Raid",
      "对局期间不能迁徙主基地"},
     {"Base facility must be installed before it can be used",
      "使用基地设施前必须先安装"},
     {"BASE SITE SECURED | EXTRACT TO UNLOCK THE LOCATION",
      "基地候选点已控制 | 撤离后解锁该地点"},
     {"BASE SITE CLEARING | INITIAL HOSTILES REMAINING ",
      "基地候选点清剿 | 初始敌人剩余 "},
     {"CLEARING UNLOCKS A SITE; MIGRATION REMAINS A LATER FACILITY SLICE",
      "清剿仅解锁候选点；迁移将在后续设施切片实现"},
     {"SITE UNLOCKED | STANDARD OUTPOST AVAILABLE BELOW",
      "地点已解锁 | 可在下方建立标准前哨"},
     {"OUTPOSTS HAVE NO STORAGE OR SERVICES | ESC BACK",
      "前哨不提供仓储或服务 | ESC 返回"},
     {"REGIONAL BASE SITES, ROUTES & OUTPOSTS",
      "区域基地候选点、路线与前哨"},
     {"CONFIRM BASE SITE CLEARING RAID", "确认基地候选点清剿行动"},
     {"DEPLOY BASE SITE CLEARING RAID", "出发执行基地候选点清剿行动"},
     {"CURRENT ONE-WAY ROUTES | RIVERSIDE ", "当前单程路线 | 河畔 "},
     {" | ASHWORKS ", " | 灰烬工场 "},
     {" | FRONTIER ", " | 边境 "},
     {"CLEAR BASE SITE TO UNLOCK", "清剿基地候选点后解锁"},
     {"CANDIDATE SITE | ", "候选地点 | "},
     {"ADVANTAGE | ", "优势 | "},
     {"DRAWBACK | ", "劣势 | "},
     {"FIXED FEATURE | ", "固定特色 | "},
     {"Ashworks Logistics Yard Relay", "灰烬工场物流场站中继点"},
     {"Ashworks Logistics Yard", "灰烬工场物流场站"},
     {"Industrial access and shorter eastern routes.",
      "便于进入工业区，并缩短东部路线。"},
     {"A noisy and exposed perimeter.", "外围嘈杂且缺少遮蔽。"},
     {"Heavy logistics workshop site.", "重型物流工坊地点。"},
     {"regional Base site clearance is unavailable during a Raid",
      "对局期间不能发起基地候选点清剿"},
     {"regional Base site is already unlocked", "基地候选点已经解锁"},
     {"regional Base site has no clearance operation",
      "基地候选点没有可执行的清剿行动"},
     {"regional Base site outpost state is invalid",
      "基地候选点关联的前哨状态无效"},
     {"regional Base site state is missing", "缺少基地候选点状态"},
     {"OUTPOST CLEARING COMPLETE | EXTRACT TO RESTORE SHORTCUTS",
      "哨所清剿完成 | 撤离后恢复捷径"},
     {"OUTPOST CLEARING | INITIAL HOSTILES REMAINING ",
      "哨所清剿 | 初始敌人剩余 "},
     {"SHORTCUTS DISRUPTED | CLEAR INITIAL HOSTILES AT ",
      "捷径已中断 | 清除以下地点的初始敌人并撤离："},
     {"EACH SETTLED SHORTCUT RAID BUILDS THREAT | ESC BACK",
      "每次使用捷径并完成行动结算都会累积威胁 | ESC 返回"},
     {"CONFIRM OUTPOST CLEARING RAID", "确认哨所清剿行动"},
     {"DEPLOY OUTPOST CLEARING RAID", "出发执行哨所清剿行动"},
     {"SHORTCUT THREAT ", "捷径威胁 "},
     {"THREAT ", "威胁 "},
     {" SAFE OPERATION(S) REMAIN", " 次安全行动剩余"},
     {"NORMAL EXITS AVAILABLE", "可使用常规撤离点"},
     {"DISRUPTED", "已中断"},
     {"NO MATERIAL OR WORLD TIME COST IN FOUNDATION V1 | ESC BACK",
      "基础版不消耗材料或世界时间 | ESC 返回"},
     {"OUTPOST GARRISON ASSIGNED | SHORTCUTS ONLINE",
      "哨所驻军已派驻 | 捷径已启用"},
     {"OUTPOST GARRISON RETURNED | SHORTCUTS OFFLINE",
      "哨所驻军已撤回 | 捷径已停用"},
     {"ASSIGN FULL GARRISON | ACTIVATE SHORTCUTS",
      "派驻满员驻军 | 启用捷径"},
     {"SHORTCUTS OFFLINE | ASSIGN 2 HEALTHY RESIDENTS",
      "捷径离线 | 请派驻 2 名健康居民"},
     {"GARRISON ASSIGNMENT BLOCKED", "无法派驻驻军"},
     {"RETURN OUTPOST GARRISON", "撤回哨所驻军"},
     {"SHORTCUTS ONLINE | ", "捷径在线 | "},
     {"ESTABLISHING CLAIMS THE SITE; IT PROVIDES NO SERVICE OR STORAGE",
      "建立仅代表占领地点；不提供服务或仓储"},
     {"FIXED SHORTCUTS REQUIRE A FULL HEALTHY GARRISON",
      "固定捷径需要健康驻军满员"},
     {"OUTPOSTS ARE ROUTE NODES, NOT SECOND BASES",
      "哨所是路线节点，不是第二基地"},
     {"REGIONAL ROUTES & LIGHT OUTPOSTS", "区域路线与轻量哨所"},
     {"NO REGIONAL OUTPOST LOCATION IS PUBLISHED",
      "当前没有已发布的区域哨所地点"},
     {"OUTPOST ESTABLISHED | STAFFING NEXT",
      "哨所已建立 | 下一步进行驻守"},
     {"OUTPOST ESTABLISHMENT BLOCKED", "无法建立哨所"},
     {"ESTABLISH LIGHT OUTPOST", "建立轻量哨所"},
     {"REGIONAL OUTPOST ESTABLISHED", "区域哨所已建立"},
     {"ACTIVE MAIN BASE | ", "当前主基地 | "},
     {"MAIN BASE", "主基地"},
     {"CORE ACTIVE", "核心运行中"},
     {"MISSING", "缺失"},
     {"BACK TO BRIEFING", "返回出击简报"},
     {"REGIONAL ROUTES", "区域路线"},
     {"ESTABLISHED", "已建立"},
     {"UNLOCKED", "已解锁"},
     {"OFFLINE", "离线"},
     {"ONLINE", "在线"},
     {"STAFF ", "驻守 "},
     {"RAID SELF-RECOVERY TARGET SET | RESERVE CARRY SPACE",
      "已设置行动自行寻回目标 | 请预留携带空间"},
     {"RAID SELF-RECOVERY TARGET CLEARED", "已取消行动自行寻回目标"},
     {"RAID RECOVERY TARGET IS NO LONGER AVAILABLE",
      "行动寻回目标已不可用"},
     {"RAID RECOVERY | ", "行动寻回 | "},
     {"RECOVER IN NEXT RAID", "在下一次行动中自行寻回"},
     {"CLEAR RAID RECOVERY TARGET", "取消行动寻回目标"},
     {"NPC TASK OR RAID RECOVERY | ONE OWNER PER RECORD",
      "NPC 委托或行动寻回 | 每条记录只有一个所有者"},
     {"CANCEL NPC | NO REFUND", "取消 NPC 委托 | 不退款"},
     {"LOST CACHE | HOLD F", "失物缓存 | 按住 F 开启"},
     {"LOST CACHE", "失物缓存"},
     {"RAID TARGET", "行动目标"},
     {"RESERVE SPACE", "预留空间"},
     {"SELECT ONE COMPLETE RECORD TO COMMISSION NPC RECOVERY",
      "选择一条完整记录以委托 NPC 寻回"},
     {"ONE WHOLE RECORD PER TASK | TASK RECORD DOES NOT AGE",
      "每项任务处理整条记录 | 任务中的记录不会老化"},
     {"COLLECT RECOVERED ASSETS", "领取寻回物品"},
     {"RECOVERY CANCELLED | NO REFUND", "寻回已取消 | 不退款"},
     {"RECOVERY COLLECTED | ", "寻回已领取 | "},
     {"RECOVERY TASK STARTED", "寻回任务已开始"},
     {"RECOVERY TASK IS STILL IN PROGRESS", "寻回任务仍在进行"},
     {"NPC RECOVERY READY", "NPC 寻回已完成"},
     {"NPC RECOVERY ACTIVE", "NPC 寻回进行中"},
     {"LOST RAID RECORDS & RECOVERY", "行动失物记录与寻回"},
     {"CANCEL | NO REFUND", "取消 | 不退款"},
     {"RECOVERY IN PROGRESS", "寻回进行中"},
     {"SELECT A LOST RAID RECORD", "请选择一条行动失物记录"},
     {"SELECT A RECORD", "请选择记录"},
     {"OLDER RECORD(S) | NEWEST FOUR SHOWN",
      "条较旧记录 | 当前显示最新四条"},
     {"START | COST ", "开始 | 费用 "},
     {" RETURNED | ", " 件带回 | "},
     {" RESULT ", " | 结果 "},
     {"REMAINING ", "剩余 "},
     {"HIGH-TENDENCY ", "高寻回倾向 "},
     {"LOW-TENDENCY ", "低寻回倾向 "},
     {"UNSAFE LOADOUT AND LOST RECORD EXPIRY - CONFIRM AGAIN",
      "配装不安全且失物记录即将到期 - 请再次确认"},
     {"LOST RECORD EXPIRES AFTER THIS RAID - CONFIRM AGAIN",
      "本次行动结算后有失物记录到期 - 请再次确认"},
     {"A LOST RAID RECORD IS AVAILABLE AT THE RAID GATE",
      "出击入口已有一条可查看的失物记录"},
     {"NO GEAR WAS CARRIED; NO LOST RECORD WAS CREATED",
      "未携带装备，因此没有生成失物记录"},
     {"DEATH OR ACTIVE QUIT CREATES A RECORD WHEN GEAR IS CARRIED",
      "携带装备时死亡或主动退出会生成失物记录"},
     {"FINAL OPPORTUNITY | NEXT RAID SETTLEMENT DESTROYS RECORD",
      "最后机会 | 下一次行动结算将销毁该记录"},
     {"RECORDS AGE ONLY WHEN A RAID SETTLES | ESC BACK",
      "失物记录仅在行动结算时老化 | ESC 返回"},
     {"WARNING: UNSAFE DEPLOY REQUIRES SECOND CONFIRMATION",
      "警告：配装不安全，需要再次确认出击"},
     {"NO RECOVERABLE LOST LOADOUTS", "当前没有可寻回的失物配装"},
     {"BACK TO RAID BRIEFING", "返回出击简报"},
     {"LOST RAID RECORDS", "行动失物记录"},
     {"WARNING: ", "警告："},
     {" RECORD(S) EXPIRE AFTER NEXT RAID SETTLEMENT",
      " 条记录将在下一次行动结算后到期"},
     {"FOLLOW-UP RAIDS ", "后续行动 "},
     {" REMAIN BEFORE FINAL OPPORTUNITY", " 次后进入最后机会"},
     {"LOST RECORDS ", "失物记录 "},
     {"ASSETS ", "资产 "},
     {"RAID ABANDONED", "已放弃行动"},
     {"BUY THE BUILDING PLAN AT THE RAID GATE", "请在出击入口购买建筑内部图"},
     {"INTERIOR LAYOUT INTELLIGENCE REQUIRED", "需要建筑内部布局情报"},
     {"INTERIOR LAYOUT INTELLIGENCE PURCHASED", "已购买永久建筑内部布局情报"},
     {"INTERIOR LAYOUT PERMANENTLY KNOWN", "已永久掌握建筑内部布局"},
     {"INTERIOR INTELLIGENCE PURCHASE BLOCKED", "无法购买建筑内部情报"},
     {"RETURN OUTSIDE TO USE TACTICAL MAP", "返回室外后可使用战术地图"},
     {"SPECIAL SITE", "特殊地点"},
     {"INTERIOR MAP UNAVAILABLE", "室内地图尚不可用"},
     {"INTERIOR MAP", "建筑内部地图"},
     {"PERMANENT INTELLIGENCE", "永久情报"},
     {"INTERIOR PLAN", "建筑内部图"},
     {"PERMANENTLY KNOWN", "已永久掌握"},
     {"M/ESC CLOSE | WORLD CONTINUES | MOVE 45%",
      "M/ESC 关闭 | 世界继续运行 | 移动速度45%"},
     {"EXCHANGE OFFICE | F ENTER", "交易所办公室 | F 进入"},
     {"OUTDOOR | F EXIT", "室外 | F 离开"},
     {"Freight Service Bay", "货运装卸间"},
     {"Exchange Office", "交易所办公室"},
     {" | F ENTER", " | F 进入"},
     {" | F EXIT", " | F 离开"},
     {"Outdoor", "室外"},
     {"TACTICAL MAP | M/ESC CLOSE | WORLD CONTINUES | MOVE 45%",
      "战术地图 | M/ESC 关闭 | 世界继续运行 | 移动速度45%"},
     {"TACTICAL MAP | FULL STATIC MAP | M/ESC CLOSE",
      "战术地图 | 完整静态地图 | M/ESC 关闭"},
     {"TACTICAL MAP | FOG OF WAR | M/ESC CLOSE",
      "战术地图 | 战争迷雾 | M/ESC 关闭"},
     {"HIGH-RISK CONTROL", "高危控制点"},
     {"RESCUE TARGET", "救援目标"},
     {"LOST CACHE", "失物缓存"},
     {"OPERATION | PERIMETER SWEEP | ACTIVE",
      "行动 | 基地外围清剿 | 进行中"},
     {"OPERATION | PERIMETER SWEEP | SECURED",
      "行动 | 基地外围清剿 | 目标完成"},
     {"TRANSPORT ACTIVE | RESOURCE ACTIVE | ENEMY ACTIVE | NO LIVE TRACKING",
      "交通情报 已启用 | 资源情报 已启用 | 敌情 已启用 | 不追踪实时位置"},
     {"CLICK INTELLIGENCE TO BUY/SELECT | ENTER DEPLOY | ESC CLOSE",
      "点击情报购买/选择 | ENTER 出击 | ESC 关闭"},
     {"INTELLIGENCE PURCHASED AND SELECTED", "情报已购买并选用"},
     {"INTELLIGENCE SELECTED FOR DEPLOYMENT", "已选择本次出击情报"},
     {"INTELLIGENCE REMOVED FROM BRIEFING", "已从本次简报移除情报"},
     {"INTELLIGENCE PURCHASE BLOCKED", "无法购买情报"},
     {"TACTICAL MAP OPEN - WORLD CONTINUES",
      "战术地图已打开 - 世界继续运行"},
     {"TACTICAL MAP CLOSED", "战术地图已关闭"},
     {"TRANSPORT MAP", "交通图"},
     {"RESOURCE MANIFEST", "物资清单"},
     {"ENEMY DOSSIER", "敌情档案"},
     {"NO LIVE TRACKING", "不追踪实时位置"},
     {"EXITS | NORMAL ", "撤离 | 常规 "},
     {" | SIGNAL ", " | 信号 "},
     {" | LIGHT ", " | 轻装 "},
     {"DIFFICULTY LOW", "难度 低"},
     {"DIFFICULTY MODERATE", "难度 中"},
     {"DIFFICULTY HIGH", "难度 高"},
     {"OPEN CENTER; EXPECT LONG SIGHTLINES", "中央开阔；预计有长距离视线"},
     {"CHOKEPOINTS CAN DELAY EXTRACTION", "狭窄通道可能拖延撤离"},
     {"DENSE COVER; PRESSURE ESCALATES QUICKLY", "掩体密集；威胁会快速升级"},
     {"COVER LAYOUT CHANGES EACH DEPLOYMENT", "每次出击的掩体布局都会变化"},
     {"BALANCED | OPEN CENTER | LONG FLANKS", "均衡 | 中央开阔 | 长距离侧翼"},
     {"MID-RANGE | CHOKEPOINTS | SAFE OUTER LOOP", "中距离 | 狭窄通道 | 安全外围路线"},
     {"CLOSE COVER | SPLIT LANES | RISKY CENTER", "近距掩体 | 分叉路线 | 高风险中央"},
     {"VARIABLE COVER | OPEN BRANCHES | GENERATED OUTDOOR",
      "可变掩体 | 开放支路 | 程序化室外区域"},
     {"Raid intelligence cannot be purchased during a Raid",
      "对局期间不能购买情报"},
     {"Raid intelligence category is invalid", "情报类别无效"},
     {"Raid intelligence map does not exist", "情报对应地图不存在"},
     {"Raid intelligence is not offered for this map", "该地图不提供此类情报"},
     {"Raid intelligence archive is full", "情报归档已满"},
     {"currency is insufficient for Raid intelligence", "货币不足，无法购买情报"},
     {"selected Raid intelligence is unavailable", "所选情报没有可用份数"},
     {"interior intelligence cannot be purchased during a Raid",
      "对局期间不能购买建筑内部情报"},
     {"interior intelligence location does not exist",
      "建筑内部情报对应地点不存在"},
     {"interior layout is already permanently known",
      "已经永久掌握该建筑内部布局"},
     {"currency is insufficient for interior intelligence",
      "货币不足，无法购买建筑内部情报"},
     {"PROFESSIONS | GENERAL", "职业 | 通用"},
     {" | MEDICAL ", " | 医疗 "},
     {" | ENGINEERING ", " | 工程 "},
     {" | COMBAT ", " | 战斗 "},
     {"STAFFING | WORKSHOP", "岗位 | 工坊"},
     {" | UNASSIGNED ", " | 未分配 "},
     {"AUTO-FILL EMPTY FACILITY JOBS", "自动填充空闲设施岗位"},
     {"BASE FACILITY WORKERS AUTO-FILLED", "已自动填充基地设施岗位"},
     {"WORKSHOP WORKER ASSIGNED", "已分配工坊人员"},
     {"WORKSHOP WORKER CLEARED", "已清空工坊岗位"},
     {"MEDICAL WORKER ASSIGNED", "已分配医疗人员"},
     {"MEDICAL WORKER CLEARED", "已清空医疗岗位"},
     {"ASSIGN BEST WORKER", "分配最合适人员"},
     {"CLEAR WORKSHOP WORKER", "清空工坊岗位"},
     {"CLEAR MEDICAL WORKER", "清空医疗岗位"},
     {"WORKSHOP UPGRADE STARTED", "工坊升级已开始"},
     {"WORKSHOP UPGRADE CANCELLED", "工坊升级已取消"},
     {"MEDICAL UPGRADE STARTED", "医疗设施升级已开始"},
     {"MEDICAL UPGRADE CANCELLED", "医疗设施升级已取消"},
     {"ANOTHER BASE CONSTRUCTION PROJECT IS ACTIVE",
      "另一个基地建设项目正在进行"},
     {"DORMITORY EXPANSION BLOCKED", "宿舍扩建被占用的建设队列阻止"},
     {"UPGRADE WORKSHOP TO LEVEL 2", "将工坊升级至2级"},
     {"UPGRADE MEDICAL TO LEVEL 2", "将医疗设施升级至2级"},
     {"CANCEL WORKSHOP UPGRADE", "取消工坊升级"},
     {"CANCEL MEDICAL UPGRADE", "取消医疗设施升级"},
     {"WORKSHOP LEVEL 2 COMPLETE", "工坊2级升级已完成"},
     {"MEDICAL LEVEL 2 COMPLETE", "医疗设施2级升级已完成"},
     {"GENERAL FALLBACK IS 50% SLOWER", "通用人员替岗耗时增加50%"},
     {"WORKSHOP LEVEL", "工坊等级"},
     {"MEDICAL LEVEL", "医疗设施等级"},
     {"UNASSIGNED RETURNS (MOVE TO RECOVER)",
      "旧版未归位物资（移动后恢复）"},
     {"ASSIGNED", "已分配"},
     {"Engineering", "工程"},
     {"Medical", "医疗"},
     {"General", "通用"},
     {"Combat", "战斗"},
     {"EMPTY", "空"},
     {"the workshop has no assigned worker", "工坊尚未分配人员"},
     {"the medical facility has no assigned worker", "医疗设施尚未分配人员"},
     {"the workshop worker profession is not eligible", "工坊人员职业不符合要求"},
     {"the medical worker profession is not eligible", "医疗人员职业不符合要求"},
     {"Base staffing is unavailable during a Raid", "对局期间不能调整基地岗位"},
     {"the Base facility staffing slot is already filled", "该设施岗位已有人员"},
     {"the Base facility staffing slot is already empty", "该设施岗位已为空"},
     {"an active facility job still requires this worker", "进行中的设施任务仍需要该人员"},
     {"no qualified healthy Base worker is available", "没有符合要求的健康基地人员"},
     {"construction has reserved the remaining healthy workers", "建设已占用剩余健康劳动力"},
     {"facility level does not match this project", "当前设施等级不符合项目要求"},
     {"RESIDENT MORALE LOW", "居民士气 低迷"},
     {"RESIDENT MORALE STABLE", "居民士气 稳定"},
     {"RESIDENT MORALE HIGH", "居民士气 高昂"},
     {"LAST DAILY REPORT", "上次每日结算"},
     {"RESIDENT MORALE", "居民士气"},
     {"PRODUCTION DURATION", "生产耗时"},
     {"APPLIES WHEN ORDER STARTS", "在订单开始时锁定"},
     {"ACTIVE EVENT", "当前事件"},
     {"NEXT ROTATION", "距离下次轮换"},
     {"Shared Meal", "共享餐食"},
     {"Restless Nights", "不安之夜"},
     {"Volunteer Cleanup", "自发清理"},
     {"Supply Anxiety", "物资焦虑"},
     {"TREND FALLING", "趋势 下降"},
     {"TREND STEADY", "趋势 平稳"},
     {"TREND RISING", "趋势 上升"},
     {"LOW DAYS", "低士气天数"},
     {"WISH +", "愿望 +"},
     {"EVENT +", "事件 +"},
     {"EFFECT +", "影响 +"},
     {"EFFECT -", "影响 -"},
     {"SCORE", "评分"},
     {"SHORTAGE", "短缺"},
     {"WORKSHOP & PRODUCTION | TEXT/GEOMETRY PLACEHOLDER",
      "工坊与生产 | 文字/图形占位"},
     {"9x19 Standard Ammunition Batch", "9×19标准弹药批次"},
     {"5.45x39 Standard Ammunition Batch", "5.45×39标准弹药批次"},
     {"7.62x51 Standard Ammunition Batch", "7.62×51标准弹药批次"},
     {"Field Weapon Maintenance Kit", "野战武器维修工具"},
     {"MANUFACTURING RECIPE SELECTED", "已选择生产配方"},
     {"SELECT RECIPE", "选择配方"},
     {"MANUFACTURING CANCELLED | INPUTS RETURNED",
      "生产已取消 | 投入物已返还"},
     {"WORKSHOP READY | INPUTS REMAIN IN OWNED INVENTORY UNTIL START",
      "工坊就绪 | 开始生产前投入物仍留在自有物品栏"},
     {"OUTPUT READY | STASH SPACE REQUIRED",
      "产物已完成 | 需要仓库空间"},
     {"CANCEL BLOCKED | STASH SPACE REQUIRED",
      "无法取消 | 需要仓库空间返还投入物"},
     {"PRODUCTION REQUIREMENTS NOT MET", "尚未满足生产条件"},
     {"PRODUCTION ACTIVE", "生产进行中"},
     {"OUTPUT READY | WORKER RELEASED", "产物已完成 | 劳动力已释放"},
     {"MANUFACTURED ITEM COLLECTED", "已领取生产物品"},
     {"MANUFACTURING STARTED", "生产已开始"},
     {"START PRODUCTION", "开始生产"},
     {"CANCEL & RETURN INPUTS", "取消并返还投入物"},
     {"COLLECT TO STASH", "领取到仓库"},
     {"REQUIRED INPUTS", "所需投入物"},
     {"OUTPUT", "产物"},
     {"WORKER COMMITTED", "名劳动力已占用"},
     {"WORKSHOP & PRODUCTION", "工坊与生产"},
     {"manufacturing can only start in Base", "只能在基地开始生产"},
     {"manufacturing can only be cancelled in Base", "只能在基地取消生产"},
     {"manufacturing output can only be collected in Base",
      "只能在基地领取生产物品"},
     {"required manufacturing input is unavailable", "缺少所需生产投入物"},
     {"insufficient healthy Base workers", "健康基地劳动力不足"},
     {"the workshop production slot is occupied", "工坊生产槽已被占用"},
     {"Stash cannot receive all reserved manufacturing inputs",
      "仓库空间不足，无法返还全部生产投入物"},
     {"Stash has no room for the manufacturing output",
      "仓库没有容纳生产物品的空间"},
     {"CHECK A DEFINITION TO AUTHORIZE AUTOMATIC USE AT DAILY NEEDS",
      "勾选物品定义，授权基地在每日需求结算时自动使用"},
     {"ITEMS KEEP THEIR REAL LOCATION UNTIL THE BASE CONSUMES THEM",
      "基地实际消耗前，物品始终保持在原位置"},
     {"NO OWNED ITEMS CAN SUPPLY THIS CATEGORY",
      "当前没有可供给此分类的自有物品"},
     {"SELECT AN OWNED SUPPLY ITEM FIRST", "请先选择一件自有供给物品"},
     {"AUTOMATIC BASE SUPPLY ENABLED", "已启用基地自动供给"},
     {"AUTOMATIC BASE SUPPLY DISABLED", "已停用基地自动供给"},
     {"OWNED SUPPLY ITEM SELECTED", "已选择自有供给物品"},
     {"SUPPLY RULE HAS NO CURRENT ITEM", "该供给规则当前没有可用物品"},
     {"Base supply policy is unavailable during a Raid",
      "对局期间不能修改基地自动供给规则"},
     {"item definition is not assigned to Base supply",
      "该物品定义尚未分配给基地供给"},
     {"Base supply item definition is unknown", "基地供给物品定义未知"},
     {"item cannot supply the selected Base category",
      "该物品不能供给所选基地分类"},
     {"no owned Base-accessible item matches this supply rule",
      "没有符合此供给规则的基地可访问自有物品"},
     {"item definition is already assigned to this Base category",
      "该物品定义已分配给此基地分类"},
     {"SELECT FROM STASH OR CARRIED CONTAINERS - ITEMS STAY PUT UNTIL USED",
      "从仓库或随身容器选择 - 确认消耗前物品保持原位"},
     {"NO BASE-ACCESSIBLE ITEMS MATCH CURRENT USES",
      "当前没有可用于基地用途的仓库或随身物品"},
     {"NEEDS ", "需要 "},
     {" FROM BASE-ACCESSIBLE INVENTORY", "，来自仓库或随身物品"},
     {"BASE-ACCESSIBLE ITEM SELECTED", "已选择仓库或随身物品"},
     {"SELECT A BASE-ACCESSIBLE ITEM", "请选择仓库或随身物品"},
     {"SELECT MATCHING ACCESSIBLE ITEM", "请选择符合要求的仓库或随身物品"},
     {"ITEM LEFT IN ORIGINAL LOCATION", "物品保持在原位置"},
     {"LEAVE IN PLACE", "保持原位"},
     {"CARRIED WEIGHT", "随身总重"},
     {"CARRIED", "随身"},
     {"RECOVERY", "待恢复"},
     {"Base allocation is unavailable during a Raid",
      "对局期间不能进行基地物资分配"},
     {"only Base-accessible personal assets can be contributed",
      "只能捐献基地内可访问的个人物品"},
     {"only Base-accessible personal assets can fulfill a Base priority",
      "只能用基地内可访问的个人物品满足基地愿望"},
     {"only Base-accessible personal assets can become construction material",
      "只能把基地内可访问的个人物品加工为建材"},
     {"PENDING RAID RETURNS - KEEP, CONTRIBUTE, BUILD, OR WISH",
      "对局待分配物资 - 保留、捐献、转为建材或满足愿望"},
     {"CONSTRUCTION CANCELLED | MATERIAL REFUNDED",
      "建设已取消 | 建材已返还"},
     {"DORMITORY EXPANSION STARTED", "宿舍扩建已开始"},
     {"ITEM PROCESSED | CONSTRUCTION MATERIAL +",
      "物品已加工 | 基地建材 +"},
     {"CANCEL & REFUND MATERIAL", "取消并返还建材"},
     {"START DORMITORY EXPANSION", "开始宿舍扩建"},
     {"EXPANSION REQUIREMENTS NOT MET", "尚未满足扩建条件"},
     {"DORMITORY EXPANSION COMPLETE", "宿舍扩建已完成"},
     {"EXPANSION IN PROGRESS", "扩建进行中"},
     {"NO FURTHER PROJECT", "没有后续建设项目"},
     {"PROCESS FOR BUILDING", "加工为建材"},
     {"NOT BUILDING MATERIAL", "不能加工为建材"},
     {"SELECT SALVAGE", "请选择回收物"},
     {"BUILDING MATERIAL", "基地建材"},
     {"WORKERS COMMITTED", "名劳动力已占用"},
     {"only pending allocation items can become construction material",
      "只有待分配物品可以加工为基地建材"},
     {"a non-empty container cannot become construction material",
      "非空容器不能加工为基地建材"},
     {"item has no Base construction material value",
      "该物品不能加工为基地建材"},
     {"Base construction material storage is full", "基地建材储量已满"},
     {"construction material can only be processed in Base",
      "只能在基地加工建材"},
     {"another Base construction project is active",
      "已有一个基地建设项目正在进行"},
     {"dormitory level does not match this project",
      "当前宿舍等级不符合该项目要求"},
     {"insufficient Base construction material", "基地建材不足"},
     {"insufficient available Base workers", "可用基地劳动力不足"},
     {"construction completion time would overflow",
      "建设完成时间超出可用范围"},
     {"construction project does not exist", "建设项目不存在"},
     {"construction project is not active", "建设项目未在进行"},
     {"construction material refund has no capacity",
      "基地建材空间不足，无法返还"},
     {"construction can only start in Base", "只能在基地开始建设"},
     {"construction can only be cancelled in Base", "只能在基地取消建设"},
     {"allocation item does not exist", "待分配物品不存在"},
     {"WORKERS", "劳动力"},
     {"AVAILABLE", "可用"},
     {"DORMITORY LEVEL", "宿舍等级"},
     {"NEXT: LEVEL", "下一项：等级"},
     {" MATERIAL /", " 建材 /"},
     {" WORKERS /", " 劳动力 /"},
     {"BUILD +", "建材 +"},
     {"RESCUED RESIDENTS", "已救援居民"},
     {"SAFE TRANSFER COMPLETE", "安全转移已完成"},
     {"HOLD F: SECURE TRANSFER", "按住 F：执行安全转移"},
     {"ORDINARY SURVIVOR", "普通幸存者"},
     {"WARNING: BED SHORTFALL", "警告：床位缺口"},
     {"DORMITORY & REST | AGGREGATED RESIDENTS",
      "宿舍与休息 | 聚合居民"},
     {"REST ADVANCES WORLD TIME AND DAILY NEEDS | MAXIMUM 12H",
      "休息会推进世界时间与每日需求 | 最多12小时"},
     {"V1 DOES NOT HEAL THE PLAYER OR SIMULATE INDIVIDUAL RESIDENTS",
      "当前版本不治疗玩家，也不模拟单个居民"},
     {"OVERCROWDED | SHORTAGE IS NON-BLOCKING",
      "床位拥挤 | 短缺不会阻止游玩"},
     {"BED CAPACITY AVAILABLE", "床位容量充足"},
     {"ORDINARY RESIDENTS", "普通居民"},
     {"RESIDENTS", "居民"},
     {"BED SHORTFALL", "床位缺口"},
     {"DAILY RATIONS", "每日口粮"},
     {"BASE OPERATIONS", "基地运转"},
     {"OPERATIONS", "运转"},
     {"RATIONS", "口粮"},
     {"/DAY", "/天"},
     {"(SECURED)", "（已确保转移）"},
     {"RESTED", "已休息"},
     {" | DAILY CYCLES ", " | 已结算每日周期 "},
     {"REST 1 HOUR", "休息1小时"},
     {"REST 6 HOURS", "休息6小时"},
     {"REST 12 HOURS", "休息12小时"},
     {"DORMITORY & REST", "宿舍与休息"},
     {"LIMITING OPERATIONS SUPPORT", "短板 运营支持"},
     {"OPERATIONS SUPPORT ", "运营支持 "},
     {"RATION STOCK", "口粮储备"},
     {" RATIONS /", " 口粮 /"},
     {"BEDS", "床位"},
     {"RESERVE", "储备"},
     {"CURRENCY ONLY | PERSONAL MEDICAL ITEMS ARE NOT CONSUMED | ESC CLOSE",
      "只支付货币 | 不消耗个人医疗物品 | ESC 关闭"},
     {"USES ONLY ITEMS ASSIGNED TO MEDICAL SUPPLY | CONSUMED ON START",
      "只使用已授权给医疗供给的物品 | 开始治疗时消耗"},
     {"RESIDENT TREATMENT STARTED | READY IN",
      "居民治疗已开始 | 剩余"},
     {"RESIDENT TREATMENT UNAVAILABLE", "当前无法进行居民治疗"},
     {"RESIDENT TREATMENT ACTIVE", "居民治疗进行中"},
     {"START RESIDENT TREATMENT", "开始居民治疗"},
     {"TREATMENT ACTIVE | READY IN", "治疗进行中 | 剩余"},
     {"AUTHORIZED SUPPLIES", "已授权医疗物资"},
     {"CONTRIBUTION", "贡献值"},
     {"RESIDENT CARE", "居民医疗"},
     {"PLAYER SERVICE", "玩家医疗"},
     {"HEALTHY", "健康"},
     {"INJURED", "伤员"},
     {"resident treatment is unavailable during a Raid",
      "对局期间不能开始居民治疗"},
     {"resident treatment is already active", "已有居民正在治疗"},
     {"no injured resident requires treatment", "没有需要治疗的受伤居民"},
     {"insufficient authorized medical supplies", "已授权医疗物资不足"},
     {"resident treatment state cannot advance", "居民治疗状态无法推进"},
     {"resident treatment supply changed", "居民治疗物资已变化"},
     {"MEDICAL SERVICE | TEXT/GEOMETRY PLACEHOLDER",
      "医疗服务 | 文字/图形占位"},
     {"TREATMENT QUOTE", "治疗报价"},
     {"PLAYER FULLY TREATED", "玩家已完成全面治疗"},
     {"TREATMENT UNAVAILABLE", "当前无法治疗"},
     {"INSUFFICIENT CURRENCY", "货币不足"},
     {"PAY & TREAT", "支付并治疗"},
     {"PLAYER HEALTH", "玩家生命"},
     {"PAIN SUPPRESSED", "疼痛已被抑制"},
     {"PAIN ACTIVE", "疼痛生效中"},
     {"NO INJURY PAIN", "没有伤势疼痛"},
     {"PAINKILLER REMAINING", "止痛药剩余"},
     {"HP", "生命"},
     {"INJURY", "伤势"},
     {"CURRENT BASE WISH - ONE LOW-PRESENCE PRIORITY",
      "基地当前愿望 - 仅显示一个低存在感目标"},
     {"PENDING RAID RETURNS - CHOOSE KEEP, CONTRIBUTE, OR WISH",
      "对局待分配物资 - 选择保留、捐献或满足愿望"},
     {"SELECTED ITEM DOES NOT MATCH WISH", "所选物品不符合当前愿望"},
     {"SELECT MATCHING PENDING ITEM", "请选择符合愿望的待分配物品"},
     {"FULFILL CURRENT BASE WISH", "满足基地当前愿望"},
     {"BASE WISH ALREADY FULFILLED", "基地当前愿望已经满足"},
     {"NEEDS", "需要"},
     {"FROM PENDING RETURNS", "来自待分配物资"},
     {"IMPROVES", "改善"},
     {"FULFILLED", "已满足"},
     {"ACTIVE", "进行中"},
     {"MISSED", "错过"},
     {"A Small Comfort", "一点小小的慰藉"},
     {"Reinforce the Perimeter", "加固基地外围"},
     {"Restore Essential Utilities", "恢复基础设施"},
     {"ESC CONTINUES | RAID EXIT RESTORES GEAR; RESCUES PERSIST",
      "ESC 继续 | 退出恢复出击前装备，已转移幸存者保留"},
     {"CLICK < > TO SELECT | ENTER DEPLOY | ESC CLOSE",
      "点击 < > 选择 | ENTER 出击 | ESC 关闭"},
     {"UP/DOWN SELECT | LEFT/RIGHT ADJUST | SHIFT COARSE | R RESET | F10/ESC "
      "CLOSE",
      "上下选择 | 左右调整 | SHIFT 大步 | R 重置 | F10/ESC 关闭"},
     {"DRAG: MOVE | CTRL: 1 | SHIFT: HALF | R: ROTATE",
      "拖拽：移动 | CTRL：1个 | SHIFT：一半 | R：旋转"},
     {"DAILY 00:00 NEEDS: 8 FOOD / 6 HYGIENE / 5 MORALE / 4 SECURITY",
      "每日 00:00 需求：8 食物 / 6 卫生 / 5 士气 / 4 安全"},
     {"NEXT DAILY NEED IN", "距离下次每日需求"},
     {"RESOLVED DAILY CYCLES", "已结算每日周期"},
     {"WORLD CLOCK SAVE FAILED", "世界时钟保存失败"},
     {"PENDING RAID RETURNS - CHOOSE KEEP OR CONTRIBUTE",
      "待分配对局收获 - 选择保留或捐献"},
     {"NO PENDING ITEMS | BASE IS READY FOR DEPLOY",
      "没有待分配物品 | 基地可以出击"},
     {"ALLOCATION & NEEDS | TEXT/GEOMETRY PLACEHOLDER",
      "资源分配与需求 | 文字/图形占位"},
     {"DEPLOY SAVES A PRE-RAID ROLLBACK POINT", "出击会保存对局前回滚点"},
     {"RETURN / REGROUP TRAVEL", "返程 / 归队耗时"},
     {"NORMAL TRAVEL", "正常返程"},
     {"FAILURE REGROUP", "失败归队"},
     {"DEPART DAY", "出发 第"},
     {"ARRIVE DAY", "抵达 第"},
     {" MIN", " 分钟"},
     {"WARNING: UNSAFE DEPLOY REQUIRES SECOND CONFIRMATION",
      "警告：不安全配装需要再次确认"},
     {"WASD MOVE  SHIFT SPRINT  E INTERACT", "WASD 移动  SHIFT 奔跑  E 交互"},
     {"RAID: LMB FIRE  RMB AIM  R RELOAD  5 MED",
      "对局：左键射击  右键瞄准  R 换弹  5 医疗"},
     {"SHIFT SPRINT  TAB INVENTORY  ESC PAUSE/CLOSE",
      "SHIFT 奔跑  TAB 物品栏  ESC 暂停/关闭"},
     {"SHIFT SPRINT  TAB INVENTORY  M TACTICAL MAP  ESC PAUSE/CLOSE",
      "SHIFT 奔跑  TAB 物品栏  M 战术地图  ESC 暂停/关闭"},
     {"TAB INVENTORY  F10 WEAPON TUNING", "TAB 物品栏  F10 武器调试"},
     {"TAB INVENTORY  M TACTICAL MAP  F10 WEAPON TUNING",
      "TAB 物品栏  M 战术地图  F10 武器调试"},
     {"LMB FIRE | RMB AIM | SHIFT SPRINT | R RELOAD",
      "左键射击 | 右键瞄准 | SHIFT 奔跑 | R 换弹"},
     {"RMB MEDICAL ITEM | TAB/ESC CLOSE", "右键使用医疗物品 | TAB/ESC 关闭"},
     {"RMB: ITEM ACTION | TAB/ESC CLOSE", "右键：物品操作 | TAB/ESC 关闭"},
     {"HIGH RISK: CONTINUOUS | SIGNAL EXTRACTION OPEN",
      "高危持续中 | 信号撤离已开放"},
     {" | Active ", " | 活动敌人 "},
     {" | Move ", " | 移动 "},
     {"STASH BLOCKED - INVENTORY PRESERVED", "仓库空间不足 - 物品保持不变"},
     {"ALL CARRIED ASSETS WERE LOST", "所有携带物品均已丢失"},
     {"NO LOST-ITEM LIST IS GENERATED", "失败不生成丢失物品清单"},
     {"RETURNED TO MAIN MENU - NO PERSISTENT PROFILE",
      "已返回主菜单 - 没有持久存档"},
     {"UNSAFE LOADOUT - CONFIRM DEPLOY AGAIN", "配装不安全 - 再次确认出击"},
     {"RESOLVE ALLOCATION & NEEDS BEFORE DEPLOY",
      "出击前请先处理资源分配与需求"},
     {"UNFINISHED RAID RESTORED TO BASE", "未完成对局已恢复到基地"},
     {"PRESS NEW GAME AGAIN TO OVERWRITE", "再次选择新游戏以覆盖存档"},
     {"RAID EXIT RESTORES PRE-RAID SAVE", "退出对局会恢复出击前存档"},
     {"DEVELOPER WEAPON TUNING - RUNTIME ONLY", "开发者武器调试 - 仅本次运行"},
     {"WEAPON ALREADY USES CONTENT DEFAULTS", "武器已使用内容默认值"},
     {"CHANGES ARE NOT SAVED", "调试修改不会保存"},
     {"F9 PERFORMANCE | F10 RUNTIME DEVELOPER PANEL",
      "F9 性能 | F10 运行时开发面板"},
     {"F10 RUNTIME DEVELOPER PANEL", "F10 运行时开发面板"},
     {"F10 DEVELOPER PANEL", "F10 开发面板"},
     {"F10 / ESC CLOSE", "F10 / ESC 关闭"},
     {"HOLD 5 / POINT / RELEASE", "按住 5 / 指向 / 松开"},
     {"BASE STASH - READ ONLY", "基地仓库 - 只读"},
     {"STASH - READ ONLY", "仓库 - 只读"},
     {"NORMAL - GRACE", "常规撤离 - 宽限中"},
     {"NORMAL EXTRACTION", "常规撤离"},
     {"SIGNAL EXTRACTION", "信号撤离"},
     {"LIGHT EXTRACTION LOCKED", "轻装撤离未开放"},
     {"ADVANCED RESOURCE OPEN", "高级资源区已开放"},
     {"ADVANCED RESOURCE LOCKED", "高级资源区未开放"},
     {"HIGH RISK ACTIVE", "高危状态已激活"},
     {"HIGH RISK CONTROL", "高危控制装置"},
     {"F: OPEN CABINET", "F：打开柜体"},
     {"F: SEARCH CABINET", "F：搜索柜体"},
     {"RETURN TO BASE", "返回基地"},
     {"CONTINUE GAME", "继续游戏"},
     {"CONFIRM NEW GAME", "确认新游戏"},
     {"NEW GAME", "新游戏"},
     {"EXIT TO MAIN MENU", "退出到主菜单"},
     {"EXIT TO DESKTOP", "退出到桌面"},
     {"KEYBOARD & MOUSE", "键盘与鼠标"},
     {"CORE EXTRACTION ALPHA", "核心撤离 Alpha"},
     {"PROJECT RAIDLINE", "Project Raidline"},
     {"SIMPLIFIED CHINESE", "简体中文"},
     {"LANGUAGE UPDATED", "语言设置已更新"},
     {"LANGUAGE CHANGED - SETTINGS SAVE FAILED", "语言已切换 - 设置保存失败"},
     {"LANGUAGE", "语言"},
     {"SETTINGS", "设置"},
     {"PAUSED", "已暂停"},
     {"CONTINUE", "继续"},
     {"BACK", "返回"},
     {"EXIT", "退出"},
     {"STORAGE & LOADOUT", "仓储与配装"},
     {"SUPPLY & RECOVERY", "供应与回收"},
     {"ALLOCATION & NEEDS", "资源分配与需求"},
     {"MEDICAL SERVICE", "医疗服务"},
     {"RAID DEPLOYMENT", "对局出击"},
     {"CHARACTER & LOADOUT", "角色与配装"},
     {"STASH - SELECT AN ITEM", "仓库 - 选择物品"},
     {"GUNSMITH QUOTE", "枪匠报价"},
     {"LIMITING", "短板"},
     {"FULL FACTORY CONDITION", "恢复出厂状态"},
     {"START FULL MAINTENANCE", "开始全面维护"},
     {"COLLECT SERVICED WEAPON", "领取维护完成的武器"},
     {"SERVICE IN PROGRESS", "维护进行中"},
     {"COLLECT - STASH BLOCKED", "领取 - 仓库空间不足"},
     {"GUNSMITH READY", "枪匠维护已完成"},
     {"STASH SPACE REQUIRED", "需要仓库空间"},
     {"SELECT A DAMAGED STASH WEAPON", "选择仓库中的受损武器"},
     {"SELECT A STASH WEAPON", "请选择仓库武器"},
     {"SERVICE STARTED | READY IN", "维护已开始 | 剩余"},
     {"WEAPON FULLY SERVICED", "武器已完成全面维护"},
     {"INSTANT", "立即完成"},
     {"SERVICED WEAPON COLLECTED", "已领取维护完成的武器"},
     {"STASH ITEM SELECTED", "已选择仓库物品"},
     {"UNKNOWN WEAPON", "未知武器"},
     {"GUNSMITH", "枪匠"},
     {"PAID", "已支付"},
     {"RECYCLE SELECTED", "回收所选物品"},
     {"CLAIM RELIEF BATCH", "领取救济批次"},
     {"RELIEF NOT REQUIRED", "当前不需要救济"},
     {"KEEP IN STASH", "保留到仓库"},
     {"CONTRIBUTE TO BASE", "捐献给基地"},
     {"CONTRIBUTION BLOCKED", "无法捐献"},
     {"SELECT ITEM FIRST", "请先选择物品"},
     {"KEEP ONLY", "只能保留"},
     {"CONFIRM UNSAFE DEPLOY", "确认不安全出击"},
     {"DEPLOY ALPHA RAID", "进入 Alpha 对局"},
     {"OBJECTIVE COMPLETE", "目标已完成"},
     {"OBJECTIVE: FIND STORAGE", "目标：找到仓储区"},
     {"OBJECTIVE: EQUIP PRIMARY WEAPON", "目标：装备主武器"},
     {"OBJECTIVE: FIND RAID GATE", "目标：找到出击口"},
     {"RAIDLINE BASE", "Raidline 基地"},
     {"RAID RESULT", "对局结果"},
     {"PLAYER DEAD", "玩家死亡"},
     {"RAID ABANDONED", "已放弃对局"},
     {"ABNORMAL EXIT - FAILED", "异常退出 - 失败"},
     {"SETTLEMENT PENDING", "等待结算"},
     {"ENTER / CLICK: RETURN TO BASE", "ENTER / 点击：返回基地"},
     {"EXTRACTION CLOSED", "撤离点关闭"},
     {"SIGNAL LOCKED", "信号撤离未开放"},
     {"HOLD F: TRIGGER", "按住 F：启动"},
     {"NO VALID PRIMARY SAVE", "没有有效主存档"},
     {"RECOVERED SAFE BACKUP", "已恢复安全备份"},
     {"PROFILE LOADED", "存档已载入"},
     {"NEW PROFILE CREATED", "新存档已创建"},
     {"RETURNED TO MAIN MENU", "已返回主菜单"},
     {"DEPLOYMENT IS NOT AVAILABLE", "当前无法出击"},
     {"PENDING ITEM SELECTED", "已选择待分配物品"},
     {"SELECT A PENDING ITEM", "请选择待分配物品"},
     {"STASH HAS NO LEGAL SPACE", "仓库没有合法空间"},
     {"ITEM MOVED TO PERSONAL STASH", "物品已移入个人仓库"},
     {"ITEM CONTRIBUTED TO BASE", "物品已捐献给基地"},
     {"BASE WISH FULFILLED", "基地愿望已满足"},
     {"SELECTED FOR RECYCLE", "已选择回收物"},
     {"RELIEF BATCH ADDED TO STASH", "救济批次已加入仓库"},
     {"EQUIPMENT UPDATED", "装备已更新"},
     {"INVENTORY UPDATED", "物品栏已更新"},
     {"NO WEAPON EQUIPPED", "未装备武器"},
     {"WEAPON ALREADY CHAMBERED", "枪膛已有弹药"},
     {"WEAPON CHAMBERED", "已上膛"},
     {"NO ROUND AVAILABLE", "没有可用弹药"},
     {"SELECT AN ASSET FIRST", "请先选择物品"},
     {"SELECT A MAGAZINE TO FILL", "请选择要压弹的弹匣"},
     {"NO COMPATIBLE STASH AMMUNITION", "仓库没有兼容弹药"},
     {"MAGAZINE FILLED", "弹匣已装满"},
     {"MAGAZINE UNLOADED TO STASH", "弹匣已卸入仓库"},
     {"NO COMPATIBLE EQUIPPED WEAPON", "没有兼容的已装备武器"},
     {"MAGAZINE INSTALLED", "弹匣已安装"},
     {"ASSET SELECTED", "已选择物品"},
     {"SELECT A CARRIED MEDKIT WHILE INJURED", "受伤时请选择携带的医疗包"},
     {"MEDKIT ACTION STARTED", "医疗包动作已开始"},
     {"CARRIED ASSET SELECTED", "已选择携带物品"},
     {"CARRIED INVENTORY UPDATED", "随身物品栏已更新"},
     {"ROTATED", "已旋转"},
     {"NO QUICK-TRANSFER SPACE", "没有快速转移空间"},
     {"INVENTORY CHANGED - TRY AGAIN", "物品栏已变化 - 请重试"},
     {"MAGAZINE UNINSTALLED", "弹匣已卸下"},
     {"MAGAZINE PACKING STARTED", "压弹动作已开始"},
     {"AMMUNITION CANNOT BE LOADED", "弹药无法装入"},
     {"MAGAZINE LOADED", "弹匣已装填"},
     {"RELOAD STARTED (2 SEC)", "换弹已开始（2秒）"},
     {"MAGAZINE CANNOT BE INSTALLED", "弹匣无法安装"},
     {"WEAPON MAINTENANCE STARTED (8 SEC)", "武器维修已开始（8秒）"},
     {"WEAPON CANNOT BE MAINTAINED", "武器无法维修"},
     {"ARMOR REPAIR STARTED (6 SEC)", "防具维修已开始（6秒）"},
     {"ARMOR CANNOT BE REPAIRED", "防具无法维修"},
     {"ASSET NO LONGER EXISTS", "物品已不存在"},
     {"MAGAZINE UNLOAD STARTED (3 SEC)", "卸弹已开始（3秒）"},
     {"MAGAZINE EMPTY OR NO CARRIED SPACE", "弹匣为空或随身空间不足"},
     {"MEDICAL ITEM CANNOT BE USED", "医疗物品无法使用"},
     {"MAGAZINE UNLOADED", "弹匣已卸弹"},
     {"MEDICAL EFFECT APPLIED", "医疗效果已应用"},
     {"WEAPON MALFUNCTION CLEARED", "武器故障已排除"},
     {"DEVELOPER RUNTIME PANEL - RUNTIME ONLY", "运行时开发面板 - 仅本次运行"},
     {"DEVELOPER RUNTIME PANEL OPEN", "运行时开发面板已打开"},
     {"DEVELOPER RUNTIME PANEL CLOSED", "运行时开发面板已关闭"},
     {"MAP FOG OF WAR: DISABLED - FULL STATIC MAP",
      "地图战争迷雾：已关闭 - 显示完整静态地图"},
     {"MAP FOG OF WAR: ENABLED", "地图战争迷雾：已启用"},
     {"MAP FOG OF WAR DISABLED - FULL STATIC MAP",
      "地图战争迷雾已关闭 - 显示完整静态地图"},
     {"MAP FOG OF WAR ENABLED", "地图战争迷雾已启用"},
     {"DEVELOPER INFINITE AMMO ENABLED", "开发者无限弹药已启用"},
     {"DEVELOPER INFINITE AMMO DISABLED", "开发者无限弹药已关闭"},
     {"INFINITE AMMO: ENABLED", "无限弹药：已启用"},
     {"INFINITE AMMO: DISABLED", "无限弹药：已关闭"},
     {"MAP FOG: ON", "地图迷雾：开启"},
     {"MAP FOG: OFF", "地图迷雾：关闭"},
     {"INFINITE AMMO: ON", "无限弹药：开启"},
     {"INFINITE AMMO: OFF", "无限弹药：关闭"},
     {"CRISIS HUD: REVEALED", "危机显示：强制揭示"},
     {"CRISIS HUD: NORMAL", "危机显示：正常规则"},
     {"ACTIVATE HIGH RISK NOW", "立即进入高危"},
     {"HIGH RISK: ACTIVE", "高危：已激活"},
     {"NO FROZEN CRISIS ON THIS MAP", "本地图没有冻结的危机"},
     {"DEVELOPER CRISIS HUD REVEAL ENABLED", "开发者危机显示已强制揭示"},
     {"DEVELOPER CRISIS HUD REVEAL DISABLED", "开发者危机显示已恢复正常规则"},
     {"DEVELOPER HIGH RISK ACTIVATED", "开发者已立即激活高危"},
     {"HIGH RISK ALREADY ACTIVE OR UNAVAILABLE", "高危已经激活或当前不可用"},
     {"CRISIS DEBUG: ", "危机调试："},
     {" | DISTRICT ", " | 分区 "},
     {" | RESOURCE POINT ", " | 资源点 "},
     {"PRESSURE DEBUG: ", "压力调试："},
     {"NEXT ", "下一波 "},
     {"DELAY ", "延迟 "},
     {" | INTERVAL ", " | 间隔 "},
     {" | WAVE ", " | 波次数量 "},
     {" | CAP ", " | 活动上限 "},
     {" | SOURCES ", " | 压力源 "},
     {"PRESSURE DEBUG: UNAVAILABLE", "压力调试：不可用"},
     {"RESET WEAPON PARAMETERS", "重置枪械参数"},
     {"CLICK OPTIONS | F10 / ESC CLOSE",
      "点击选项 | F10 / ESC 关闭"},
     {"CLICK ROW OR - / + | F10 / ESC CLOSE",
      "点击参数行或 - / + | F10 / ESC 关闭"},
     {"F TOGGLE MAP FOG | F10 / ESC CLOSE",
      "F 切换地图迷雾 | F10 / ESC 关闭"},
     {"F MAP FOG | I INFINITE AMMO | F10 / ESC CLOSE",
      "F 地图迷雾 | I 无限弹药 | F10 / ESC 关闭"},
     {"F MAP FOG | I INFINITE AMMO | F10/ESC CLOSE",
      "F 地图迷雾 | I 无限弹药 | F10/ESC 关闭"},
     {"F MAP FOG | F10/ESC CLOSE", "F 地图迷雾 | F10/ESC 关闭"},
     {"DEVELOPER PERFORMANCE OVERLAY OPEN", "开发者性能面板已打开"},
     {"DEVELOPER PERFORMANCE OVERLAY CLOSED", "开发者性能面板已关闭"},
     {"RAID PERFORMANCE | F9 CLOSE", "对局性能 | F9 关闭"},
     {"FRAME EVENT/UPDATE/PRESENT/PACING/TOTAL MS",
      "帧 事件/更新/渲染提交/节奏等待/总计 毫秒"},
     {"NO FRAME SAMPLES", "暂无帧样本"},
     {"SAMPLES", "样本"},
     {"SIM ENEMIES", "模拟 敌人"},
     {"BLOCKERS", "障碍"},
     {"SUBSTEPS", "子步"},
     {"NAV QUERY", "寻路查询"},
     {"DEFERRED", "延后"},
     {"NEIGHBOR", "邻居候选"},
     {"LOS TESTS", "视线检测"},
     {"MOVE TESTS", "移动碰撞检测"},
     {"RUNTIME WEAPON TUNING UPDATED", "运行时武器参数已更新"},
     {"RUNTIME WEAPON TUNING RESET", "运行时武器参数已重置"},
     {"MEDICAL SELECTION CANCELLED", "已取消医疗选择"},
     {"NO CHEST RIG MEDICAL ITEM", "胸挂中没有医疗物品"},
     {"MEDICAL ACTION STARTED", "医疗动作已开始"},
     {"SELECTED MEDICAL ITEM IS NOT APPLICABLE", "所选医疗物品当前不适用"},
     {"UNLOAD MAGAZINE (3 SEC)", "卸出弹药（3秒）"},
     {"UNLOAD ALL TO STASH", "全部卸入仓库"},
     {"USE MEDKIT (5 SEC)", "使用医疗包（5秒）"},
     {"USE MEDKIT", "使用医疗包"},
     {"APPLY BANDAGE (2 SEC)", "使用绷带（2秒）"},
     {"APPLY BANDAGE", "使用绷带"},
     {"APPLY TOURNIQUET (4 SEC)", "使用止血带（4秒）"},
     {"APPLY TOURNIQUET", "使用止血带"},
     {"TAKE PAINKILLER (2 SEC)", "服用止痛药（2秒）"},
     {"TAKE PAINKILLER", "服用止痛药"},
     {"CHAMBER ROUND", "手动上膛"},
     {"RELOADING", "换弹中"},
     {"PACKING MAGAZINE", "压弹中"},
     {"HEALING", "治疗中"},
     {"BANDAGING", "包扎中"},
     {"APPLYING TOURNIQUET", "使用止血带中"},
     {"TAKING PAINKILLER", "服用止痛药中"},
     {"UNLOADING MAGAZINE", "卸弹中"},
     {"MAINTAINING WEAPON", "维修武器中"},
     {"REPAIRING ARMOR", "维修防具中"},
     {"SWITCHING WEAPON", "切换武器中"},
     {"EXTRACTING", "撤离中"},
     {"PREPARING RAID", "正在准备突袭"},
     {"VALIDATING RAID REQUEST", "正在验证出击请求"},
     {"PREPARING FROZEN RAID SNAPSHOT", "正在准备本局冻结快照"},
     {"GENERATING DISTRICTS, ROADS AND LANDMARKS",
      "正在生成区域、道路和地标"},
     {"FREEZING RESOURCE POINTS, LOOT AND ENEMIES",
      "正在冻结资源点、战利品和敌人"},
     {"BUILDING RAID WORLD", "正在建立对局世界"},
     {"SAVING DEPLOYMENT STATE", "正在保存出击状态"},
     {"RAID READY", "对局已准备完成"},
     {"GENERATING LARGE OUTDOOR MAP", "正在生成大型室外地图"},
     {"PLACING DISTRICTS, ROADS AND LANDMARKS",
      "正在布置区域、道路和地标"},
     {"VALIDATING ROUTES AND EXTRACTION POINTS",
      "正在验证路线和撤离点"},
     {"PLEASE WAIT - BUILDING FROZEN RAID SNAPSHOT",
      "请稍候 - 正在建立本局冻结快照"},
     {"PLEASE WAIT - PROGRESS FOLLOWS ACTUAL DEPLOYMENT STAGES",
      "请稍候 - 进度对应实际出击阶段"},
     {"HEAVY BLEEDING", "重度流血"},
     {"LIGHT BLEEDING", "轻度流血"},
     {"NO BLEEDING", "未流血"},
     {"HEAVY BLEED", "重度流血"},
     {"LIGHT BLEED", "轻度流血"},
     {"NO BLEED", "未流血"},
     {"ARMOR HIT", "护甲受击"},
     {"READY", "可执行"},
     {"NOT NEEDED", "无需使用"},
     {"OVERRIDDEN", "已覆盖"},
     {"CONTENT DEFAULT", "内容默认值"},
     {"NO ACTIVE WEAPON", "没有当前武器"},
     {"EMPTY", "空"},
     {"BLOCKED", "不可执行"},
     {"INSTALL", "安装"},
     {"REPAIR", "维修"},
     {"MERGE", "合并"},
     {"SWAP", "交换"},
     {"LOAD", "装填"},
     {"MOVE", "移动"},
     {"DROP", "丢弃"},
     {"PLAYER", "玩家"},
     {"CONTAINER", "容器"},
     {"ONLY", "仅限"},
     {"EXTRACTED", "撤离成功"},
     {"FOOD", "食物"},
     {"HYGIENE", "卫生"},
     {"MORALE", "士气"},
     {"SECURITY", "安全"},
     {"STABLE", "稳定"},
     {"SUPPORTED", "充足"},
     {"STRAINED", "紧张"},
     {"CRITICAL", "危急"},
     {"Riverside Service Road", "河畔服务道路"},
     {"Old Relay Access", "旧中继站通道"},
     {"Riverside Service Cut", "河畔服务捷径"},
     {"Freight Service Cut", "货运服务捷径"},
     {"Frontier Service Cut", "边境服务捷径"},
     {"Greyline Access Road", "灰线通行道路"},
     {"Riverside Main Road", "河畔主路"},
     {"Ashworks Freight Road", "灰烬工场货运道路"},
     {"Frontier Trunk Road", "边境干道"},
     {"Old Service Relay", "老旧服务中继站"},
     {"Greyline Yard", "灰线场站"},
     {"Greyline West", "灰线西区"},
     {"Greyline Depot", "灰线仓库"},
     {"Riverside Checkpoint", "河畔检查站"},
     {"Ashworks Yard", "灰烬工场"},
     {"Frontier Exchange", "边境交换站"},
     {"BALANCED | OPEN CENTER | LONG FLANKS", "均衡 | 中央开阔 | 长线侧路"},
     {"MID-RANGE | CHOKEPOINTS | SAFE OUTER LOOP",
      "中距离 | 咽喉点 | 安全外围环线"},
     {"CLOSE COVER | SPLIT LANES | RISKY CENTER",
      "近距掩体 | 分离路线 | 高风险中央"},
     {"Weapon Maintenance Kit", "武器维修工具"},
     {"15-round Pistol Magazine", "15发手枪弹匣"},
     {"30-round Magazine", "30发弹匣"},
     {"Damaged Electronics", "损坏电子元件"},
     {"Armor Repair Kit", "防具维修工具"},
     {"Basic Body Armor", "基础防弹衣"},
     {"Basic Helmet", "基础头盔"},
     {"Scout Helmet", "轻型侦察头盔"},
     {"Heavy Assault Helmet", "重型突击头盔"},
     {"Light Protective Vest", "轻型防护背心"},
     {"Heavy Plate Armor", "重型插板甲"},
     {"Small Chest Rig", "小型胸挂"},
     {"Patrol Chest Rig", "巡逻胸挂"},
     {"Assault Chest Rig", "突击胸挂"},
     {"Small Backpack", "小型背包"},
     {"Field Backpack", "野战背包"},
     {"Expedition Backpack", "远征背包"},
     {"9mm Ammunition", "9毫米弹药"},
     {"9x19 Enhanced Ball", "9×19增强普通弹"},
     {"5.45x39 Standard Ball", "5.45×39标准普通弹"},
     {"5.45x39 Enhanced Ball", "5.45×39增强普通弹"},
     {"7.62x51 Standard Ball", "7.62×51标准普通弹"},
     {"7.62x51 Enhanced Ball", "7.62×51增强普通弹"},
     {"5.45x39 30-round Magazine", "5.45×39 30发弹匣"},
     {"7.62x51 20-round Magazine", "7.62×51 20发弹匣"},
     {"7.62x51 100-round Box", "7.62×51 100发弹箱"},
     {"Medical Kit", "医疗包"},
     {"Basic Medkit", "基础医疗包"},
     {"Tourniquet", "止血带"},
     {"Painkiller", "止痛药"},
     {"Bandage", "绷带"},
     {"Scrap Parts", "废旧零件"},
     {"Sealed Water Bottles", "密封饮用水"},
     {"Canned Meal", "罐装餐食"},
     {"Cleaning Supplies", "清洁用品"},
     {"Compact Game Set", "便携游戏套装"},
     {"First Aid Stock", "急救物资"},
     {"Industrial Fasteners", "工业紧固件"},
     {"Copper Wire Spool", "铜线卷"},
     {"Machine Tool Set", "机修工具组"},
     {"Precision Components", "精密组件"},
     {"Pistol", "手枪"},
     {"Rifle", "步枪"},
     {"Compact 5.45 Carbine", "紧凑型5.45卡宾枪"},
     {"Service 5.45 Rifle", "制式5.45步枪"},
     {"7.62 Precision Rifle", "7.62精确射手步枪"},
     {"7.62 Support Machine Gun", "7.62支援机枪"},
     {"Cola", "可乐"},
     {"BODY ARMOR", "防弹衣"},
     {"CHEST RIG", "胸挂"},
     {"BACKPACK", "背包"},
     {"HELMET", "头盔"},
     {"LONG GUN", "长枪"},
     {"SIDEARM", "手枪"},
     {"MAG", "弹匣"},
     {"UTIL", "工具"},
     {"CURRENCY", "货币"},
     {"DURABILITY", "耐久"},
     {"WEIGHT", "重量"},
     {"PROTECTION", "防护"},
     {"POCKETS", "分区"},
     {"CELLS", "格"},
     {"COMPOSITE", "复合材料"},
     {"METAL", "金属"},
     {"SOFT", "软质"},
     {"CONDITION", "状态"},
     {"CAPACITY", "容量"},
     {"AMMUNITION", "弹药"},
     {"AMMO", "弹药"},
     {"HEALTH", "生命"},
     {"OBJECTIVE", "目标"},
     {"SCORE", "得分"},
     {"RAID", "对局"},
     {"WAREHOUSE", "仓储"},
     {"STASH", "仓库"},
     {"UNKNOWN", "未知"},
     {"medical asset does not exist", "医疗物品不存在"},
     {"medical asset is not carried into the Raid", "医疗物品未携带进对局"},
     {"medical asset has no usable charge", "医疗物品没有可用次数"},
     {"medical effect is not applicable", "医疗效果当前不适用"},
     {"allocation item does not exist", "待分配物品不存在"},
     {"only pending allocation items can be contributed",
      "只有待分配物品可以捐献"},
     {"a non-empty container cannot be contributed", "非空容器不能捐献"},
     {"Base priority is not initialized", "基地愿望尚未初始化"},
     {"Base priority is already fulfilled", "基地当前愿望已经满足"},
     {"Base priority definition is unknown", "基地愿望定义未知"},
     {"priority item does not exist", "愿望物品不存在"},
     {"only pending allocation items can fulfill a Base priority",
      "只有待分配物品可以满足基地愿望"},
     {"a non-empty container cannot fulfill a Base priority",
      "非空容器不能用于满足基地愿望"},
     {"selected item does not match the current Base priority",
      "所选物品不符合基地当前愿望"},
     {"Base priority reward would exceed resource capacity",
      "愿望收益会超过基地资源容量"},
     {"item has no Base contribution value", "物品没有基地贡献值"},
     {"supply definition does not exist", "供应定义不存在"},
     {"item is not available from fixed supply", "固定供应中没有该物品"},
     {"player medical service is unavailable during a Raid",
      "对局期间无法使用玩家医疗服务"},
     {"player does not need Base medical treatment",
      "玩家当前不需要基地医疗"},
     {"player medical quote exceeds the supported currency range",
      "玩家医疗报价超出支持范围"},
     {"currency is insufficient for player medical service",
      "货币不足，无法使用玩家医疗服务"},
     {"Base rest is unavailable during a Raid",
      "对局期间无法在基地休息"},
     {"Base rest must be between 1 and 12 hours",
      "基地休息时长必须为1至12小时"},
     {"world clock cannot advance by the requested rest",
      "世界时钟无法推进所请求的休息时长"},
     {"gunsmith service is unavailable during a Raid",
      "对局期间无法使用枪匠服务"},
     {"gunsmith service already has an active job",
      "枪匠已有进行中的维护"},
     {"gunsmith weapon does not exist", "枪匠维护的武器不存在"},
     {"gunsmith weapon must be stored directly in the Stash",
      "枪匠维护的武器必须直接存放在仓库中"},
     {"asset is not a serviceable weapon", "所选物品不是可维护武器"},
     {"weapon already has factory condition", "武器已经处于出厂状态"},
     {"gunsmith quote exceeds the supported currency range",
      "枪匠报价超出支持范围"},
     {"currency is insufficient for gunsmith service",
      "货币不足，无法使用枪匠服务"},
     {"gunsmith service timeline cannot advance",
      "枪匠维护时间无法推进"},
     {"gunsmith service has no active job", "枪匠没有进行中的维护"},
     {"gunsmith service asset ownership is invalid",
      "枪匠维护物品的所有权状态无效"},
     {"gunsmith service is still in progress", "枪匠维护仍在进行"},
     {"Stash has no legal space for serviced weapon",
      "仓库没有可放置维护武器的合法空间"},
     {"currency is insufficient", "货币不足"},
     {"asset cannot be recycled", "物品不能回收"},
     {"currency would overflow", "货币数值会溢出"},
     {"profile is not eligible for relief", "当前不符合救济条件"},
     {"requested quantity is outside the source stack", "请求数量超出来源堆叠"},
     {"requested orientation is not supported", "不支持请求的方向"},
     {"only Settlement can place assets into pending allocation",
      "只有结算可以把物品放入待分配区"},
     {"destination container does not exist", "目标容器不存在"},
     {"asset does not fit inside the destination", "物品无法放入目标位置"},
     {"pending allocation cannot swap an asset back into intake",
      "待分配物品不能通过交换返回待分配区"},
     {"partial movement requires a stackable empty or matching target",
      "部分移动需要空位或同类可堆叠目标"},
     {"selected quantity cannot be merged completely", "所选数量无法完整合并"},
     {"destination asset disappeared", "目标物品已不存在"},
     {"stacks from different relief batches cannot be combined",
      "不同救济批次的堆叠不能合并"},
     {"destination stack is full", "目标堆叠已满"},
     {"destination overlaps more than one asset", "目标位置与多个物品重叠"},
     {"pending allocation must be kept before it can be equipped",
      "待分配物品需先保留到仓库才能装备"},
     {"asset cannot use the requested equipment slot",
      "物品不能使用该装备栏位"},
     {"occupied equipment slot cannot be swapped", "已占用装备栏位无法交换"},
     {"magazine or ammunition does not exist", "弹匣或弹药不存在"},
     {"ammunition is incompatible with magazine", "弹药与弹匣不兼容"},
     {"requested rounds do not fit", "请求的弹药数量无法装入"},
     {"magazine has no rounds to unload", "弹匣没有可卸出的弹药"},
     {"destination cannot hold unloaded ammunition",
      "目标位置无法容纳卸出的弹药"},
     {"weapon or magazine does not exist", "武器或弹匣不存在"},
     {"magazine is incompatible with weapon", "弹匣与武器不兼容"},
     {"magazine must be stored before installation",
      "弹匣安装前必须位于容器中"},
     {"weapon or magazine disappeared during installation",
      "安装期间武器或弹匣已不存在"},
     {"weapon has no installed magazine", "武器没有已安装弹匣"},
     {"asset is not a magazine-fed weapon", "物品不是弹匣供弹武器"},
     {"weapon is already chambered", "武器已上膛"},
     {"no round is available to chamber", "没有可上膛的弹药"},
     {"weapon malfunction must be cleared", "必须先排除武器故障"},
     {"weapon has no malfunction", "武器没有故障"},
     {"weapon is broken", "武器已损坏"},
     {"weapon is dry", "武器无弹"},
     {"round chambered", "弹药已上膛"},
     {"maintenance kit or weapon does not exist", "维修工具或武器不存在"},
     {"maintenance kit cannot repair itself", "维修工具不能维修自身"},
     {"maintenance capability or capacity is unavailable",
      "维修能力或容量不足"},
     {"weapon does not require maintenance", "武器当前无需维修"},
     {"maintenance would produce no result", "维修不会产生效果"},
     {"maintenance kit has no usable capacity", "维修工具没有可用容量"},
     {"armor repair kit or armor does not exist", "防具维修工具或防具不存在"},
     {"armor repair kit cannot repair itself", "防具维修工具不能维修自身"},
     {"armor maintenance capability or capacity is unavailable",
      "防具维修能力或容量不足"},
     {"armor does not require maintenance", "防具当前无需维修"},
     {"armor material has no maintenance cost", "防具材料没有维修消耗定义"},
     {"armor repair kit cannot produce a legal repair",
      "防具维修工具无法完成合法维修"},
     {"armor repair cost exceeds kit capacity", "防具维修消耗超过工具容量"},
     {"transaction ID must not be empty", "事务编号不能为空"},
     {"profile revision is stale", "存档版本已过期"},
     {"profile revision cannot advance", "存档版本无法推进"},
     {"asset does not exist", "物品不存在"},
     {"weapon does not exist", "武器不存在"},
     {"magazine does not exist", "弹匣不存在"},
     {"persistence is not configured", "存档系统未配置"},
     {"weapon malfunction", "武器故障"},
     {"medical charge could not be committed", "医疗次数提交失败"},
     {"continuous healing revision overflow", "持续治疗版本溢出"},
     {"continuous healing could not be committed", "持续治疗提交失败"},
     {"continuous healing world sync failed", "持续治疗世界同步失败"},
     {"medical status revision overflow", "医疗状态版本溢出"},
     {"incoming damage could not be committed", "受到伤害提交失败"},
     {"primary save was invalid; recovered safe backup",
      "主存档无效；已恢复安全备份"},
     {"no valid primary or backup save", "没有有效主存档或备份"},
     {"save directory could not be created", "无法创建存档目录"},
     {"temporary save could not be written", "无法写入临时存档"},
     {"temporary save failed read-back validation", "临时存档回读校验失败"},
     {"pending Raid recovery backup could not be prepared",
      "无法准备未完成对局恢复备份"},
     {"safe backup could not be updated", "无法更新安全备份"},
     {"safe backup could not be atomically replaced", "无法原子替换安全备份"},
     {"initial safe backup could not be created", "无法创建初始安全备份"},
     {"primary save could not be atomically replaced", "无法原子替换主存档"},
     {"primary save committed; recovery backup could not be installed",
      "主存档已提交；恢复备份安装失败"},
     {"Recoil control", "后坐力控制"},
     {"Stability", "稳定性"},
     {"Handling speed", "操控速度"},
     {"Ergonomics", "人机工效"},
     {"Accuracy", "精准度"},
     {"Shot interval", "射击间隔"},
     {"Base damage", "基础伤害"},
     {"Effective range", "有效射程"},
     {"Maximum range", "最大射程"},
     {"Logical ballistic speed", "逻辑弹道速度"},
     {"High-scope maximum speed", "高倍镜最大移动速度"},
     {"High-scope control accel", "高倍镜控制加速度"},
     {"Spread per shot", "单发散布增长"},
     {"Recoil lateral ratio", "后坐力横向比例"},
     {"Recoil bend duration", "后坐力偏转时长"},
     {"Moving spread fraction", "移动散布比例"},
     {"Sprinting spread fraction", "奔跑散布比例"},
     {"Reticle motion spread rate", "准星移动散布速率"},
     {"Near-distance spread scale", "近距离散布缩放"},
     {"Effective-range distance bloom", "有效射程距离扩散"},
     {"Right-click aim accuracy", "右键瞄准精准度"},
     {"Right-click aim stability", "右键瞄准稳定性"},
     {"Weak tracer length", "弱曳光长度"},
     {"Weak tracer opacity", "弱曳光透明度"},
     {"Weak tracer lifetime", "弱曳光持续时间"},
     {"recoil speed", "后坐速度"},
     {"max spread", "最大散布"},
     {"recovery", "恢复"},
     {"control accel", "控制加速度"},
     {"min spread", "最小散布"},
     {"charge(s)", "次"},
     {"ASSET", "物品"},
     {"Stationary", "静止"},
     {"Normal", "常规"},
     {"Attack", "攻击"},
     {"Unaware", "未警觉"},
     {"Alerted", "已警觉"},
     {"Searching", "搜索中"},
     {"Engage", "交战"},
     {"Support", "支援"},
     {"Grab", "抓取"},
     {"Scratch", "抓挠"},
     {"Bite", "撕咬"},
     {"Idle", "待机"},
     {"Windup", "前摇"},
     {"Active", "生效"},
     {"Recovery", "后摇"},
     {"OffBalance", "失衡"},
     {"Unknown", "未知"},
     {"Action: None", "操作：无"},
     {"Action: MoveUp", "操作：向上移动"},
     {"Action: MoveDown", "操作：向下移动"},
     {"Action: MoveLeft", "操作：向左移动"},
     {"Action: MoveRight", "操作：向右移动"},
     {"Action: Fire", "操作：射击"},
     {"Action: Interact", "操作：交互"},
     {"Action: ToggleInventory", "操作：切换物品栏"},
     {"Action: ToggleTacticalMap", "操作：切换战术地图"},
     {"Action: Sprint", "操作：奔跑"},
     {"Player HP", "玩家生命"},
     {"Enemies", "敌人"},
     {"Alerted", "已警觉"},
     {"Searching", "搜索中"},
     {"Ground Items", "地面物品"},
     {"Inventory Items", "物品栏物品"},
     {"Interact", "交互"},
     {"Inventory: Cabinet [Open]", "物品栏：柜体[已打开]"},
     {"Inventory: Player [Open]", "物品栏：玩家[已打开]"},
     {"Inventory: Tab [Closed]", "物品栏：Tab[已关闭]"},
     {"Raid Time: NO HARD LIMIT", "对局时间：无硬性限制"},
     {"Raid Time", "对局时间"},
     {"NORMAL EXTRACTION OPEN", "常规撤离已开放"},
     {"HIGH RISK SOON", "即将进入高危"},
     {"REGULAR", "常规阶段"},
     {"Pressure wave", "压力波次"},
     {" | Next ", " | 下一波 "},
     {"Profile assets", "存档物品"},
     {"Currency", "货币"},
     {"stacks", "堆"},
     {"units", "件"},
     {"Settlement", "结算"},
     {"Flow", "流程"},
     {"Session", "会话"},
     {"Enemy AI: none", "敌人 AI：无"},
     {"Enemy AI: defeated", "敌人 AI：已击败"},
     {"Lead AI", "领队 AI"},
     {"moving", "移动中"},
     {"holding", "原地警戒"},
     {"stagger", "硬直"},
     {"Player controlled: no", "玩家受控：否"},
     {"Player controlled", "玩家受控"},
     {"Weapon: NONE", "武器：无"},
     {"Chamber", "枪膛"},
     {"Magazine", "弹匣"},
     {"MALFUNCTION - SWEEP MOUSE", "故障 - 快速移动鼠标排除"},
     {"PAIN SUPPRESSED", "疼痛已抑制"},
     {"PAIN", "疼痛"},
     {"Extraction", "撤离"},
     {"STORED", "已存入"},
     {"STACKS", "堆"},
     {"UNITS", "件"},
     {"LOST", "丢失"},
     {"Resolve Stash capacity before returning", "返回前请先解决仓库容量"},
     {"RECOIL DECEL", "后坐减速度"},
     {"RMB AIM", "右键瞄准"},
     {"DUR", "耐久"},
     {"SUPPLY & RECOVERY", "供应与回收"},
     {"BUY", "购买"},
     {"RECYCLE", "回收"},
     {"RELIEF-LOCKED", "救济锁定"},
     {"LAST SHORTFALL", "上次短缺"},
     {"SHORTAGE NEVER BLOCKS PLAY", "短缺不会阻止游玩"},
     {"NIGHT", "夜晚"},
     {"DAY", "白天"},
     {"MAP", "地图"},
     {"CAN FIRE NOW", "当前可射击"},
     {"COMPATIBLE MAGAZINE ROUNDS", "发兼容弹匣弹药"},
     {"NEEDS CHAMBER/RELOAD", "需要上膛/换弹"},
     {"COMPATIBLE ROUNDS", "发兼容弹药"},
     {"NO USABLE AMMUNITION", "没有可用弹药"},
     {"DEPLOY BLOCKED", "无法出击"},
     {"PENDING ITEM(S) AT", "件待分配物品位于"},
     {"REV", "版本"},
     {"BASE", "基地"},
     {"HP", "生命"},
     {"Score", "得分"},
     {"Raid", "对局"},
     {"NONE", "无"},
     {"Medical Ki", "医疗包"},
     {"9mm Ammuni", "9毫米弹药"},
     {"30-round M", "30发弹匣"},
     {"15-round P", "15发手枪弹匣"},
     {"Small Ches", "小型胸挂"},
     {"Small Back", "小型背包"},
     {"Basic Medk", "基础医疗包"},
     {"Weapon Mai", "武器维修工具"},
     {"Armor Repa", "防具维修工具"},
     {"Basic Helm", "基础头盔"},
     {"Basic Body", "基础防弹衣"},
     {"Scrap Part", "废旧零件"},
     {"Damaged El", "损坏电子元件"},
     {"Sealed Wat", "密封饮用水"},
     {"Canned Mea", "罐装餐食"},
     {"Cleaning S", "清洁用品"},
     {"Compact Ga", "便携游戏套装"},
     {"First Aid ", "急救物资"},
     {"Industrial", "工业紧固件"},
     {"Copper Wir", "铜线卷"},
     {"Machine To", "机修工具组"},
     {"Precision ", "精密组件"},
     {"Used Book", "旧书"},
     {"Toilet Paper", "卫生纸"},
     {"Toilet Pa", "卫生纸"},
     {"RECREATION", "娱乐"},
     {"MEDICAL", "医疗"},
     {" | OWN ", " | 持有 "},
     {"TRANSPORT ", "交通情报 "},
     {"RESOURCE ", "资源情报 "},
     {"ENEMY ", "敌情 "},
     {"SELECTED", "已选择"},
     {"CLOSED", "关闭"},
     {"MATURE", "成熟"},
     {"STRATEGIC", "战略"},
     {"BASIC", "基础"},
     {"LOCKED", "锁定"},
     {"OPEN", "开放"},
     {"ASSIGNED", "已分配"},
     {"PER ITEM", "每件"}});

void replaceAll(std::string &text, std::string_view source,
                std::string_view destination) {
  std::size_t offset{};
  while ((offset = text.find(source, offset)) != std::string::npos) {
    text.replace(offset, source.size(), destination);
    offset += destination.size();
  }
}
} // namespace

const char *uiLanguageCode(UiLanguage language) noexcept {
  return language == UiLanguage::SimplifiedChinese ? "zh-CN" : "en-US";
}

const char *uiLanguageDisplayName(UiLanguage language) noexcept {
  return language == UiLanguage::SimplifiedChinese ? "简体中文" : "English";
}

UiLanguage toggledUiLanguage(UiLanguage language) noexcept {
  return language == UiLanguage::SimplifiedChinese
             ? UiLanguage::English
             : UiLanguage::SimplifiedChinese;
}

std::string localizeUiText(UiLanguage language, std::string_view englishText) {
  std::string localized{englishText};
  if (language == UiLanguage::English || localized.empty()) {
    return localized;
  }
  for (const auto &[english, chinese] : kSimplifiedChineseTranslations) {
    if (englishText == english) {
      return std::string{chinese};
    }
  }
  for (const auto &[english, chinese] : kSimplifiedChineseTranslations) {
    replaceAll(localized, english, chinese);
  }
  return localized;
}

UiLanguage loadUiLanguage(const std::filesystem::path &settingsPath) noexcept {
  try {
    std::ifstream stream{settingsPath};
    if (!stream) {
      return UiLanguage::SimplifiedChinese;
    }
    nlohmann::json document;
    stream >> document;
    const std::string code = document.value("language", "zh-CN");
    return code == "en-US" ? UiLanguage::English
                           : UiLanguage::SimplifiedChinese;
  } catch (...) {
    return UiLanguage::SimplifiedChinese;
  }
}

bool saveUiLanguage(const std::filesystem::path &settingsPath,
                    UiLanguage language) noexcept {
  try {
    std::filesystem::create_directories(settingsPath.parent_path());
    std::ofstream stream{settingsPath, std::ios::trunc};
    if (!stream) {
      return false;
    }
    stream << nlohmann::json{{"language", uiLanguageCode(language)}}.dump(2);
    stream.flush();
    return stream.good();
  } catch (...) {
    return false;
  }
}
